/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bloodms;

import Controller.BloodReceived;
import Controller.Doner;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anthonydonx
 */
public class DonerJF extends javax.swing.JFrame {

    /**
     * Creates new form DonerJF
     */
    public DonerJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Doner_Register_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Doner_Register_Name = new javax.swing.JTextField();
        Doner_Register_Age = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Doner_Register_Weight = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Doner_Register_Address = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Doner_Register_Tp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Doner_Register_Sex = new javax.swing.JComboBox();
        Doner_Register_BloodType = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        Doner_Register_RHD = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        Doner_Register_Save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Doner_profile_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Doner");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 81, -1));

        Doner_Register_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Doner_Register_idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Doner_Register_idKeyTyped(evt);
            }
        });
        jPanel3.add(Doner_Register_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 11, 242, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 81, -1));
        jPanel3.add(Doner_Register_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 202, -1));
        jPanel3.add(Doner_Register_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 49, 242, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 81, -1));
        jPanel3.add(Doner_Register_Weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 202, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Weight in kg");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 81, -1));
        jPanel3.add(Doner_Register_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 87, 242, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 81, -1));

        Doner_Register_Tp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Doner_Register_TpActionPerformed(evt);
            }
        });
        jPanel3.add(Doner_Register_Tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 202, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("T.P");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 81, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sex");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 137, 81, -1));

        Doner_Register_Sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel3.add(Doner_Register_Sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 137, 242, -1));

        Doner_Register_BloodType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "AB", "O" }));
        jPanel3.add(Doner_Register_BloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 193, 242, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Blood Type");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, 81, -1));

        Doner_Register_RHD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Positive", "Negative" }));
        jPanel3.add(Doner_Register_RHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 202, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RHD");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 81, -1));

        Doner_Register_Save.setText("Save");
        Doner_Register_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Doner_Register_SaveActionPerformed(evt);
            }
        });
        jPanel3.add(Doner_Register_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 262, 110, -1));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 262, 102, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/back (2).jpg"))); // NOI18N
        jLabel11.setText("jLabel2");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 750, 300));

        jTabbedPane2.addTab("Register/Update", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Doner_profile_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Doner_profile_idKeyReleased(evt);
            }
        });
        jPanel4.add(Doner_profile_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 242, -1));

        jLabel10.setText("ID");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Donation"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 715, 202));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/back (2).jpg"))); // NOI18N
        jLabel12.setText("jLabel2");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 750, 300));

        jTabbedPane2.addTab("Doner profile", jPanel4);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, -1, 290));

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setBackground(new java.awt.Color(0, 102, 204));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("X");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 40, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Doner_Register_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Doner_Register_idKeyReleased
        if (evt.getKeyCode() != 10) {
            String ID = Doner_Register_id.getText();
            if (ID.length() == 10) {
                try {
                    ResultSet rs = new Doner().getDoner(ID);
                    while (rs.next()) {
                        JOptionPane.showMessageDialog(rootPane, "Doner already exits!.Click to load");
                        Doner_Register_Save.setText("Update");
                        Doner_Register_id.setText(rs.getString("id"));
                        Doner_Register_Name.setText(rs.getString("name"));
                        Doner_Register_Age.setText(rs.getString("age"));
                        Doner_Register_Weight.setText(rs.getString("weight"));
                        Doner_Register_Address.setText(rs.getString("address"));
                        Doner_Register_Tp.setText(rs.getString("tp"));
                        Doner_Register_Sex.setSelectedItem(rs.getString("sex"));
                        Doner_Register_BloodType.setSelectedItem(rs.getString("bloodtype"));
                        Doner_Register_RHD.setSelectedItem(rs.getString("rhd"));
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }

            }
        }
    }//GEN-LAST:event_Doner_Register_idKeyReleased

    private void Doner_Register_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Doner_Register_idKeyTyped

    }//GEN-LAST:event_Doner_Register_idKeyTyped

    private void Doner_Register_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Doner_Register_SaveActionPerformed
        String Tp = Doner_Register_Tp.getText();
        if (Tp.length() == 10)
        {
        
        String ID = Doner_Register_id.getText();
        String Name = Doner_Register_Name.getText();
        String age = Doner_Register_Age.getText();
        String weight = Doner_Register_Weight.getText();
        String Address = Doner_Register_Address.getText();
        //String Tp = Doner_Register_Tp.getText();
        String Sex = Doner_Register_Sex.getSelectedItem().toString();
        String BloodType = Doner_Register_BloodType.getSelectedItem().toString();
        String RHD = Doner_Register_RHD.getSelectedItem().toString();
        if (Doner_Register_Save.getText().equals("Save")) {
            String msg = new Doner().saveDoner(ID, Name, age, weight, Address, Tp, Sex, BloodType, RHD);
            JOptionPane.showMessageDialog(rootPane, msg);

        } else {
            String msg = new Doner().updateDoner(ID, Name, age, weight, Address, Tp, Sex, BloodType, RHD);
            JOptionPane.showMessageDialog(rootPane, msg);

            if (msg.equals("Update completed !")) {
                DonerReset();
            }
        }
        
        }
        else{ 
           JOptionPane.showMessageDialog(null, "Enter correct Telephone details","",JOptionPane.ERROR_MESSAGE);
                
        }
        
    }//GEN-LAST:event_Doner_Register_SaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DonerReset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Doner_profile_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Doner_profile_idKeyReleased
    
        try {
              DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        if (evt.getKeyCode()==10) {
       ResultSet rs =     new BloodReceived().getGRN(Doner_profile_id.getText());
        while (rs.next()) {
                Vector v = new Vector();
                
                v.add(rs.getString("receivedate"));
                v.add(rs.getString("volume"));
               
                dtm.addRow(v);
            }
        }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_Doner_profile_idKeyReleased

    private void Doner_Register_TpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Doner_Register_TpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Doner_Register_TpActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonerJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonerJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonerJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonerJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonerJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Doner_Register_Address;
    private javax.swing.JTextField Doner_Register_Age;
    private javax.swing.JComboBox Doner_Register_BloodType;
    private javax.swing.JTextField Doner_Register_Name;
    private javax.swing.JComboBox Doner_Register_RHD;
    private javax.swing.JButton Doner_Register_Save;
    private javax.swing.JComboBox Doner_Register_Sex;
    private javax.swing.JTextField Doner_Register_Tp;
    private javax.swing.JTextField Doner_Register_Weight;
    private javax.swing.JTextField Doner_Register_id;
    private javax.swing.JTextField Doner_profile_id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
public void DonerReset() {
        Doner_Register_Save.setText("Save");
        Doner_Register_id.setText("");
        Doner_Register_Name.setText("");
        Doner_Register_Age.setText("");
        Doner_Register_Weight.setText("");
        Doner_Register_Address.setText("");
        Doner_Register_Tp.setText("");
        Doner_Register_Sex.setSelectedIndex(0);
        Doner_Register_BloodType.setSelectedIndex(0);
        Doner_Register_RHD.setSelectedIndex(0);
    }

}
