package pharmacy;


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import pharmacy.code.dbconnect;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */
public final class inventory extends javax.swing.JFrame {

    /**
     * Creates new form inventory
     */
    
    Connection con= null;
    PreparedStatement ast= null;
    ResultSet rs= null;
 String No;
 String Medicine_ID;
 String Medicine_Name;
 String Medicine_Type;
 String Quantity;
 String Manufacture_Name;
 String Manufacture_Date;
 String Expiry_Date;
    public inventory() {
        initComponents();
        con= dbconnect.connect();
        tableload();
    }

    
    public void tableload()
        {
            try{
              String sql="SELECT * FROM med_request  ";
              ast=con.prepareStatement(sql); 
              rs =ast.executeQuery();
              rqmed.setModel(DbUtils.resultSetToTableModel(rs));
              
              String sql1="SELECT * FROM med_assaign  ";
              ast=con.prepareStatement(sql1); 
              rs =ast.executeQuery();
              assmed.setModel(DbUtils.resultSetToTableModel(rs));
               
            }
            catch(Exception e)
            {
                
            }
            
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rqmed = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextField_location = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        assmed = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rqmed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rqmed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rqmedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rqmed);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 740, 180));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Assigned Medicine");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 180, -1));

        jTextField_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_locationActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_location, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Location");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 55, -1));

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 74, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Qty");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 50, 17));

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyKeyTyped(evt);
            }
        });
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 130, -1));

        assmed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(assmed);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 730, 151));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/out.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 30, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Requested Medicine");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 210, 35));

        jButton2.setText("Assaign");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/logo2.jpg"))); // NOI18N
        jLabel14.setText("jLabel5");
        jLabel14.setPreferredSize(new java.awt.Dimension(940, 110));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/15106-illustration-of-a-red-close-button-pv.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 30, 30));

        jButton1.setText("Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 950, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//        Medicine_Name.setText("");
  //      Medicine_ID.setText("");
        qty.setText("");
    //    location.setSelectedIndex(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    private void qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyTyped
       char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) ||(c==KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyKeyTyped

    private void rqmedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rqmedMouseClicked
        //try {
        try{
            
    
            
//                   String sql1="SELECT * FROM `med_reg` WHERE (Quantity<=100)";
//              ast=con.prepareStatement(sql1); 
//              rs =ast.executeQuery();
//              JOptionPane.showMessageDialog(null,"This  Medicine is reaching to out of stock!");
//                    
            
            int row=rqmed.getSelectedRow();
             jTextField_location.setText((String) (rqmed.getModel().getValueAt(row, 3)));
              qty.setText( (rqmed.getModel().getValueAt(row, 2)).toString());}
        catch(Exception e){
        System.out.println(" ");
        }
//            String sr= "select location, qty from request where location='"+table_click+"' and qty='"+table_clic+"'";
//            ast=con.prepareStatement(sr); 
//              rs =ast.executeQuery();
//              
//              if(rs.next()){
//              
//              String add1=rs.getString("location");
//             jTextField_location.setText(add1);
//              
//              String add2=rs.getString("qty");
//              qty.setText(add2);
//              
//              
//              }
              
              
//        } catch (Exception e) {
//        }
        
        selectrow();        // TODO add your handling code here:
    }//GEN-LAST:event_rqmedMouseClicked

    private void jTextField_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_locationActionPerformed

        


// TODO add your handling code here:
    }//GEN-LAST:event_jTextField_locationActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    
        
        
       int sum;
        String qtny = qty.getText();
        sum =Integer.parseInt(qtny);
        int Quantitysum =Integer.parseInt(qtny);
        Quantitysum =Quantitysum-sum;
        String Location=jTextField_location.getText();
        //String loc =locbox.getText();

        if(sum<0){
            JOptionPane.showMessageDialog(null, "not available");
        }
        else
        {
            int x=JOptionPane.showConfirmDialog(rootPane, "Do you want to assign this record?");

            if(x==0){
                try {

                    
             
                    
                    
//                 String medid=Medicine_ID.getText();
//           String mednm=Medicine_Name.getText();
//                  String Location=location.getSelectedItem().toString();
//                    String qt=qtny.getText();
                    con = dbconnect.connect();
                    java.sql.Statement s=con.createStatement();
                    s.execute("INSERT INTO `HMS`.`med_assaign` (`Medicine_Name`, `Quantity`, `Location`) VALUES ('"+Medicine_Name+"', '"+qtny+"', '"+Location+"')");
                    s.executeUpdate("UPDATE `HMS`.`med_reg` SET `Quantity` = '"+Quantitysum+"' WHERE `med_reg`.`Medicine_Name` = '"+Medicine_Name+"'");
                    tableload();
    //                    details();Medicine_Name

                    }
                    catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }        




// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        phmcy_hm o1= new  phmcy_hm();
        o1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
            HashMap param=new HashMap();
//param.put("reportParameterName",valueForTheParameter);
staff.MyiReportViewer viewer=new staff.MyiReportViewer("C:\\Users\\X55OL\\Desktop\\reports\\pharmacy.jasper",param);
viewer.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();;
        }   
        
    }//GEN-LAST:event_jButton1ActionPerformed
public void selectrow(){
    try {
        int r=rqmed.getSelectedRow();
 No=rqmed.getValueAt(r, 0).toString();
 Medicine_ID=rqmed.getValueAt(r, 1).toString();
 Medicine_Name=rqmed.getValueAt(r, 1).toString();
 Medicine_Type=rqmed.getValueAt(r, 2).toString();
 Quantity=rqmed.getValueAt(r, 3).toString();
 Manufacture_Name=rqmed.getValueAt(r, 5).toString();
 Manufacture_Date=rqmed.getValueAt(r, 6).toString();
 Expiry_Date=rqmed.getValueAt(r, 7).toString();
    } catch (Exception e) {
        System.out.println(" ");
    }
 

         
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable assmed;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_location;
    private javax.swing.JTextField qty;
    private javax.swing.JTable rqmed;
    // End of variables declaration//GEN-END:variables
}
