/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package LAB;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SACHI
 */
public class Addreport extends javax.swing.JFrame {
    Connection conn= null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    EmailForm y=new EmailForm();


    int timeRun =0;
   
    public Addreport() {
        initComponents();
        conn=DBaccess.ConnectDb();
        update_Report();
        currentdate();
        addCombobox1();
        
       new Thread()
       {
           public void run()
           {
               while (timeRun== 0){
                   
                   Calendar cal= new GregorianCalendar();
                   int hour=cal.get(Calendar.HOUR);
                   int min=cal.get(Calendar.MINUTE);
                   int sec=cal.get(Calendar.SECOND);
                   int type=cal.get(Calendar.AM_PM);
                   
                   String Day_Night="";
                   
                   if(type == 1)
                   {
                       Day_Night="PM";
                       
                   }
                   else
                   {
                       Day_Night="AM";
                       
                   }
                   String time = hour+":"+min+":"+sec+" "+Day_Night;
                   D_clock.setText(time);
                   
               }
           
           }
       
       
       }.start();
    }
 public void currentdate(){
            
              Calendar set=new GregorianCalendar(); 
              int year=set.get(Calendar.YEAR);
              int month=set.get(Calendar.MONTH);
              int day=set.get(Calendar.DAY_OF_MONTH);
              
              
              Get_date.setText(year+"-"+(month+1)+"-"+day);
            
            
        }
    
 public void update_Report(){
        
       try{
            String sql="select * from report_details";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Table_report.setModel(DbUtils.resultSetToTableModel(rs));
       }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
           
       }
 }
 void addCombobox1(){
   test_type.addItem("Scan");
  test_type.addItem("Blood");
   test_type.addItem("MRI");
    test_type.addItem("X-Ray");
   test_type.addItem("Urine");
test_type.addItem("Full Body Ceckup");
    
   
}
 public void close(){
        WindowEvent winClosingEvent= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 }
 
 public void ManualEntry(){
    
    
    
    
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_report = new javax.swing.JTable();
        seach_details = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        delete_row = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        D_clock = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Get_date = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        save_report = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edit_id = new javax.swing.JLabel();
        Name_txt = new javax.swing.JTextField();
        Sex_Info = new javax.swing.JComboBox();
        Age = new javax.swing.JTextField();
        Date_edit = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        test_type = new javax.swing.JComboBox();
        st_edit = new javax.swing.JComboBox();
        info_in = new javax.swing.JTextField();
        Gen_Doc = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table_report.setBackground(new java.awt.Color(204, 204, 255));
        Table_report.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_reportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_report);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 870, 180));

        seach_details.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(seach_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 262, -1));

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 115, -1));

        delete_row.setText("Delete");
        delete_row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_rowActionPerformed(evt);
            }
        });
        getContentPane().add(delete_row, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 109, -1));

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 109, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/out.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 10, 50, -1));

        D_clock.setFont(new java.awt.Font("DS-Digital", 1, 14)); // NOI18N
        D_clock.setForeground(new java.awt.Color(255, 255, 255));
        D_clock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D_clock.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(D_clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 139, 21));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Date-:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, 21));

        Get_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Get_date.setForeground(new java.awt.Color(255, 255, 255));
        Get_date.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Get_date.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(Get_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 95, 21));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Time-:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 63, 21));

        save_report.setText("Edit");
        save_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_reportActionPerformed(evt);
            }
        });
        getContentPane().add(save_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 100, -1));

        jButton2.setText("Sed Email");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 410, 100, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/logo2.jpg"))); // NOI18N
        jLabel14.setText("jLabel5");
        jLabel14.setPreferredSize(new java.awt.Dimension(940, 110));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Test Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Age:-");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sex:-");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Patient Name:-");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Patient ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        edit_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit_id.setForeground(new java.awt.Color(204, 51, 0));
        jPanel1.add(edit_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 154, 24));

        Name_txt.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(Name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 190, -1));

        Sex_Info.setBackground(new java.awt.Color(204, 204, 255));
        Sex_Info.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel1.add(Sex_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 112, -1));

        Age.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 110, -1));

        Date_edit.setBackground(new java.awt.Color(204, 204, 255));
        Date_edit.setDateFormatString(" yyyy-MM-dd");
        jPanel1.add(Date_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 190, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Report Details");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Situation");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Test Type");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        test_type.setBackground(new java.awt.Color(204, 204, 255));
        test_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test_typeActionPerformed(evt);
            }
        });
        jPanel1.add(test_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 169, -1));

        st_edit.setBackground(new java.awt.Color(204, 204, 255));
        st_edit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select...", "Pending", "Succesfull", "Cancel" }));
        st_edit.setToolTipText("");
        st_edit.setActionCommand("");
        st_edit.setName(""); // NOI18N
        jPanel1.add(st_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 169, -1));

        info_in.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(info_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 170, -1));

        Gen_Doc.setText("Report view and Print");
        Gen_Doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gen_DocActionPerformed(evt);
            }
        });
        jPanel1.add(Gen_Doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 177, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover3.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 200));

        jButton3.setText("Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 100, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 940, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String pid=seach_details.getText();
        
        String sql="select * from report_details where Patient_ID LIKE '%"+pid+"%'";
        try {
            pst=conn.prepareStatement(sql);
          rs = pst.executeQuery();
          Table_report.setModel(DbUtils.resultSetToTableModel(rs) );
          
        } catch (SQLException ex) {
          
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            update_Report(); 
            seach_details.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void delete_rowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_rowActionPerformed
        try{
          int row=Table_report.getSelectedRow();
          
          String Table_click2=(Table_report.getModel().getValueAt(row, 0).toString());
          
          int x=JOptionPane.showConfirmDialog(rootPane,"Do you Want To Delete..?");
          
          if(x==0){
          String sql="delete from report_details where Patient_ID='"+Table_click2+ "'";
         pst=conn.prepareStatement(sql);
         pst.execute();
          }
         
       update_Report();
          
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e); 
    }                           
    }//GEN-LAST:event_delete_rowActionPerformed

    private void Gen_DocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gen_DocActionPerformed
       
       
       
        
       close();
       ReportCreate s=new ReportCreate();
       s.setVisible(true);
    }//GEN-LAST:event_Gen_DocActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        close();
        TestRequest d=new  TestRequest();
        d.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void test_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test_typeActionPerformed

    }//GEN-LAST:event_test_typeActionPerformed

    private void save_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_reportActionPerformed
        String pattern="[0-9]+";
        try{
            String sql="update report_details set Patient_ID=?,Patient_Name=?,sex=?,Patient_Age=?,Test_Date=?,Test_Type=?,Status=?,Test_Details=? where Patient_ID=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,edit_id.getText());
            pst.setString(2,Name_txt.getText());
            String value1=Sex_Info.getSelectedItem().toString();
            pst.setString(3,value1);
            pst.setString(4,Age.getText());
            String age=Age.getText();
            if(age.length()==2 && age.matches(pattern))
            {
                pst.setString(5,((JTextField)Date_edit.getDateEditor().getUiComponent()).getText());
                String value2=test_type.getSelectedItem().toString();
                pst.setString(6,value2);
                String value3=st_edit.getSelectedItem().toString();
                pst.setString(7,value3);
                pst.setString(8,info_in.getText());
                pst.setString(9,edit_id.getText());

                pst.execute();
                JOptionPane.showMessageDialog(null,"Success");
                edit_id.setText("");
                Name_txt.setText("");
                Sex_Info.setSelectedIndex(0);
                Age.setText("");
                ((JTextField)Date_edit.getDateEditor().getUiComponent()).setText("");
                test_type.setSelectedIndex(0);
                st_edit.setSelectedIndex(0);
                info_in.setText("");
                
                update_Report();
            }
            else{
                JOptionPane.showMessageDialog(null,"Invalid Age","", JOptionPane.ERROR_MESSAGE);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }

    }//GEN-LAST:event_save_reportActionPerformed

    private void Table_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_reportMouseClicked
       try {int row=Table_report.getSelectedRow();
          String add1=(Table_report.getModel().getValueAt(row,0).toString()); 
          String  add2=(Table_report.getModel().getValueAt(row,1).toString());  
          String  add3=(Table_report.getModel().getValueAt(row,2).toString()); 
          String  add4=(Table_report.getModel().getValueAt(row,3).toString()); 
           String  add5=(Table_report.getModel().getValueAt(row,4).toString()); 
            String  add6=(Table_report.getModel().getValueAt(row,5).toString());
          String  add7=(Table_report.getModel().getValueAt(row,6).toString());
           String  add8=(Table_report.getModel().getValueAt(row,7).toString());
           
           edit_id.setText(add1);
           Name_txt.setText(add2);
           Sex_Info.setSelectedItem(add3);
           Age.setText(add4);
           DateFormat format = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
              Date date = format.parse(add5);
              Date_edit.setDate(date);
             test_type.setSelectedItem(add6);
             st_edit.setSelectedItem(add7);
            info_in.setText(add8);
               } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Please select Data Row");
        }
    }//GEN-LAST:event_Table_reportMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
          int row=Table_report.getSelectedRow();
          
          String Table_click1=(Table_report.getModel().getValueAt(row, 0).toString()); 
           String Status1=(Table_report.getModel().getValueAt(row, 6).toString());
          
          if(Status1.contentEquals("Succesfull")){
              
             y.GetId(Table_click1);
             
             y.setVisible(true);
             //close();
             
              
          }
          else{
              
               JOptionPane.showMessageDialog(null, "Report is not completed");
              
          }
        
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Please select Data Row");
    
}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
               try {
            HashMap param=new HashMap();
//param.put("reportParameterName",valueForTheParameter);
staff.MyiReportViewer viewer=new staff.MyiReportViewer("C:\\Users\\X55OL\\Desktop\\reports\\lab.jasper",param);
viewer.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addreport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JLabel D_clock;
    private com.toedter.calendar.JDateChooser Date_edit;
    private javax.swing.JButton Gen_Doc;
    private javax.swing.JLabel Get_date;
    private javax.swing.JTextField Name_txt;
    private javax.swing.JComboBox Sex_Info;
    private javax.swing.JTable Table_report;
    private javax.swing.JButton delete_row;
    private javax.swing.JLabel edit_id;
    private javax.swing.JTextField info_in;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save_report;
    private javax.swing.JTextField seach_details;
    private javax.swing.JComboBox st_edit;
    private javax.swing.JComboBox test_type;
    // End of variables declaration//GEN-END:variables
}
