/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package LAB;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import javax.swing.JOptionPane;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.MessagingException;
import javax.mail.Message.RecipientType;
/**
 *
 * @author SACHI
 */
public class EmailForm extends javax.swing.JFrame {
     Connection conn= null;
    ResultSet rs=null;
    PreparedStatement pst=null;

    
    
    /**
     * Creates new form EmailForm
     */
    public EmailForm() {
        initComponents();
         conn=DBaccess.ConnectDb();
     
        
    }
    public static boolean sendEmail(String from,String Password,String message,String to[]){
        String host="smtp.gmail.com";
        Properties prop=System.getProperties();
        prop.put("mail.smtp.starttls.enable",true);
        prop.put("email.smtp.host", prop);
        prop.put("email.smtp.user", from);
        prop.put("email.smtp.password",Password);
        prop.put("email.smtp.port",587);
        prop.put("email.smtp.auth","true");
        
         Session session=Session.getDefaultInstance(prop,null);
         MimeMessage mimemessage=new MimeMessage(session);
         
         try{
         mimemessage.setFrom(new InternetAddress(from));
         InternetAddress [] toAdress=new InternetAddress[to.length];
        for(int i=0;i<to.length;i++){
            
            toAdress[i]=new InternetAddress(to[i]);
        } 
          for(int i=0;i<toAdress.length;i++){ 
               
              mimemessage.setSubject("Colombo East Base Hospital Test Report");
              
            
        }
          
          mimemessage.setText(message);
          Transport ransport=session.getTransport("smtp");
          ransport.connect(host,from,Password);
          ransport.sendMessage(mimemessage, mimemessage.getAllRecipients());
          ransport.close();
          return true;
         }catch(MessagingException me){
            JOptionPane.showMessageDialog(null, me);  
             
             
         }
        return false;
        
        
    }
   
    
public void GetId(String Table_click2)throws ParseException{
    
    EmailP.setText(Table_click2);
    
    
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EmailP = new javax.swing.JTextField();
        EmailAdd = new javax.swing.JTextField();
        SearchEmail = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jLabel1.setText("Patient ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 89, -1, -1));

        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 126, -1, -1));

        EmailP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailPActionPerformed(evt);
            }
        });
        getContentPane().add(EmailP, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 86, 169, -1));
        getContentPane().add(EmailAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 120, 169, -1));

        SearchEmail.setText("Search");
        SearchEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEmailActionPerformed(evt);
            }
        });
        getContentPane().add(SearchEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 85, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 102, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 40, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EmailPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailPActionPerformed

    private void SearchEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEmailActionPerformed
     
     String id1=EmailP.getText();
      String sql="select pid,email from p2 where pid LIKE '%"+id1+"%'";
    
    try{
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        
        while(rs.next()){
                
                EmailAdd.setText(rs.getString("email"));
                
            }
        
        
    }catch(Exception e){
      JOptionPane.showMessageDialog(null, e);  
        
    } 
    
            
    }//GEN-LAST:event_SearchEmailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String s1=EmailAdd.getText();
        
        String [] to={s1};
   if(EmailForm.sendEmail("udaranilan@gmail.com",
       "sachira2275746", 
       "message to Reciepent",to))System.out.println("email Send Succesfully");
       
           else System.out.println("have some erro");
              
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
       
        
        
    
    
        
     
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmailForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailAdd;
    private javax.swing.JTextField EmailP;
    private javax.swing.JButton SearchEmail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
