/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test2;

import java.sql.Connection;
import java.sql.ResultSet;
//import static java.time.Clock.system;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Isurunath
 */
public final class Add_Ward extends javax.swing.JInternalFrame {

    /**
     * Creates new form Add_Ward
     */
    public Add_Ward() {
        initComponents();
        tabelload();
    }
    
    public void tabelload(){
        
        try{
        
        
        Connection c = DBcon.connect();
        java.sql.Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("SELECT * FROM ward");
        
        
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
        }catch (Exception e){
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        wardno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nobeds = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(900, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Ward Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Location");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        location.setBackground(new java.awt.Color(204, 204, 255));
        location.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 90, -1));

        name.setBackground(new java.awt.Color(204, 204, 255));
        name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 90, -1));

        wardno.setBackground(new java.awt.Color(204, 204, 255));
        wardno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(wardno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 90, -1));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 600, 190));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 102));
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 80, 30));

        Update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Update.setForeground(new java.awt.Color(0, 51, 102));
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/update.png"))); // NOI18N
        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/Delete.png"))); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/add.png"))); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 100, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Number Of Beds");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        nobeds.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(nobeds, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 90, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int r=jTable1.getSelectedRow();
        String iusr=jTable1.getValueAt(r, 0).toString();
        String ipwd=jTable1.getValueAt(r, 1).toString();
        String iacnt=jTable1.getValueAt(r, 2).toString();
        String Nobeds=jTable1.getValueAt(r, 3).toString();

        wardno.setText(iusr);
        name.setText(ipwd);
        location.setText(iacnt);
        nobeds.setText(Nobeds);

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //ward.dispose();
        //ward().dispose();
        //System.exit(0);
        //new ward().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed

        String no = wardno.getText();
        String Name = name.getText();
        String loc = location.getText();
        String Nobeds = nobeds.getText();

        try {

            Connection c = DBcon.connect();
            java.sql.Statement s =c.createStatement();
            s.executeUpdate("update ward set wardNO = '"+no+"',name = '"+Name+"',location = '"+loc+"',no_beds='"+Nobeds+"' where wardNO = '"+no+"'" );
            tabelload();

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,e);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try{

            String no = wardno.getText();
            Connection c = DBcon.connect();
            java.sql.Statement s = c.createStatement();
            s.executeUpdate("delete from ward where wardno = '"+no+"'");
            tabelload();

        } catch(Exception e){

            JOptionPane.showConfirmDialog(null,e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String ward = wardno.getText();
        String Name = name.getText();
        String loc = location.getText();
        int Nobeds = Integer.parseInt(nobeds.getText());
        
        if(ward.equals("")||Name.equals(" ")||loc.equals("")){
            JOptionPane.showMessageDialog(null,"Please fill the form to add wards");
        }
        else{
            try{

                Connection c = DBcon.connect();
                java.sql.Statement s = c.createStatement();
                s.executeUpdate("Insert into ward(wardNO,name,location,no_beds) values ('"+ward+"','"+Name+"','"+loc+"','"+Nobeds+"')");
                tabelload();

            } catch(Exception e){

                JOptionPane.showMessageDialog(null,"Ward is alreay used");
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nobeds;
    private javax.swing.JTextField wardno;
    // End of variables declaration//GEN-END:variables
}
