/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test2;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Isurunath
 */
public class NewJInternalFrame extends javax.swing.JInternalFrame {

    
    String y;
    
    public NewJInternalFrame() {
        initComponents();
        
    }

   
    
    public NewJInternalFrame(String x) {
        initComponents();
    
        y = x;
//        l1.setText(y);
//        
//        l1.setVisible(true);
//        l2.setVisible(false);
//        l3.setVisible(false);
        load();
        
        JLabel lbl = new JLabel("sdf");
             lbl.setVisible(true);
             this.add(lbl);
             
        
        //NewJInternalFrame.add(lbl);
        //p.add(lbl);
       
    }
    
    public final void ll(){
    
    JLabel lbl = new JLabel("sdf");
    lbl.setVisible(true);
    //NewJInternalFrame.add(lbl);
    //p.add(lbl);
    
    //Container c = NewJInternalFrame.getContentPane();
    this.add(lbl);
    }
    
   
    public final void load(){
     try {
             
             Connection c = DBcon.connect();
             java.sql.Statement s=c.createStatement();
             ResultSet rs = s.executeQuery("SELECT bedID FROM Bed where wardID = '"+y+"'");
             
             
            // int count=0;
             String bed;
             
             
             
             //JLabel[] labels = {l1,l2,l3};
             JButton[] gbutton = {B01,B02,B03,B04,B05,B06,B07,B08,B09,B10,B11,B12,B13,B14,B15,B16,B17,B18,B19,B20,B21,B22,B23,B24
                               ,B25,B26,B27,B28,B29,B30,B31,B32,B33,B34,B35,B36,B37,B38,B39,B40};
             
             JLabel[] label = {jLabel1,jLabel2,jLabel3,jLabel4,jLabel5,jLabel6,jLabel7,jLabel8,jLabel9,jLabel10,jLabel11,jLabel12,jLabel13,jLabel14,jLabel15,jLabel16,jLabel17,jLabel18,jLabel19,jLabel20,jLabel21,jLabel22,jLabel23,jLabel24,jLabel25,jLabel26,jLabel27,jLabel28,jLabel29,jLabel30,jLabel31,jLabel32,jLabel33,jLabel34,jLabel35,jLabel36,jLabel37,jLabel38,jLabel39,jLabel40};
             for(int i=0;i<40;i++){
                 gbutton[i].setVisible(false);
                 label[i].setVisible(false);
             }
             
             ImageIcon icon = new ImageIcon("C:\\Users\\X55OL\\Documents\\NetBeansProjects\\HMS\\src\\test2\\images\\bed.jpg");
             
             
             while(rs.next()){
            
             //labels[count].setVisible(true);
             bed = rs.getString("bedID");
             
             int i =0;
             
             for(i=0;i<40;i++){
                 
                 if(bed.equals(gbutton[i].getName())){
                     gbutton[i].setIcon(icon);
                     break;
                   } 
                  else {
                 }
                 
             }
             
            
             
             
            // count= count +1;
             
             
             /* labels[1].setText(rs.getString("wardID"));
             (z).setVisible(true);
            
             l3.setText(rs.getString("patientID"));*/
             
             
             }
             
             s=c.createStatement();
             int no;
             rs = s.executeQuery("SELECT * FROM ward where wardNO = '"+y+"'");
             while(rs.next()){
                 no = Integer.parseInt(rs.getString("no_beds"));
                 for(int z=0;z<no;z++){
                 gbutton[z].setVisible(true);
                 label[z].setVisible(true);
                 
                 name.setText(rs.getString("name"));
                 location.setText(rs.getString("location"));
                 nobeds.setText(rs.getString("no_beds"));
                 
             }
                 
                 break;
             }
     }
             catch (Exception e){
                 
                 JOptionPane.showConfirmDialog(null,e);
             }
     
             
    }
    
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        B01 = new javax.swing.JButton();
        B03 = new javax.swing.JButton();
        B07 = new javax.swing.JButton();
        B06 = new javax.swing.JButton();
        B08 = new javax.swing.JButton();
        B09 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        B13 = new javax.swing.JButton();
        B14 = new javax.swing.JButton();
        B11 = new javax.swing.JButton();
        B12 = new javax.swing.JButton();
        B15 = new javax.swing.JButton();
        B02 = new javax.swing.JButton();
        B17 = new javax.swing.JButton();
        B18 = new javax.swing.JButton();
        B04 = new javax.swing.JButton();
        B05 = new javax.swing.JButton();
        B30 = new javax.swing.JButton();
        B16 = new javax.swing.JButton();
        B19 = new javax.swing.JButton();
        B29 = new javax.swing.JButton();
        B36 = new javax.swing.JButton();
        B21 = new javax.swing.JButton();
        B20 = new javax.swing.JButton();
        B22 = new javax.swing.JButton();
        B23 = new javax.swing.JButton();
        B24 = new javax.swing.JButton();
        B25 = new javax.swing.JButton();
        B26 = new javax.swing.JButton();
        B27 = new javax.swing.JButton();
        B28 = new javax.swing.JButton();
        B31 = new javax.swing.JButton();
        B32 = new javax.swing.JButton();
        B33 = new javax.swing.JButton();
        B34 = new javax.swing.JButton();
        B35 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        B38 = new javax.swing.JButton();
        B37 = new javax.swing.JButton();
        B39 = new javax.swing.JButton();
        B40 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nobeds = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setName("form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 450));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B01.setName("B01"); // NOI18N
        B01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B01ActionPerformed(evt);
            }
        });
        jPanel2.add(B01, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 60, 35));

        B03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B03.setName("B03"); // NOI18N
        B03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B03ActionPerformed(evt);
            }
        });
        jPanel2.add(B03, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 60, 35));

        B07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B07.setName("B07"); // NOI18N
        B07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B07ActionPerformed(evt);
            }
        });
        jPanel2.add(B07, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 60, 35));

        B06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B06.setName("B06"); // NOI18N
        B06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B06ActionPerformed(evt);
            }
        });
        jPanel2.add(B06, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 64, 35));

        B08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B08.setName("B08"); // NOI18N
        B08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B08ActionPerformed(evt);
            }
        });
        jPanel2.add(B08, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 60, 35));

        B09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B09.setName("B09"); // NOI18N
        B09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B09ActionPerformed(evt);
            }
        });
        jPanel2.add(B09, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 60, 35));

        B10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B10.setName("B10"); // NOI18N
        B10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B10ActionPerformed(evt);
            }
        });
        jPanel2.add(B10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 60, 35));

        B13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B13.setName("B13"); // NOI18N
        B13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B13ActionPerformed(evt);
            }
        });
        jPanel2.add(B13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 60, 35));

        B14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B14.setName("B14"); // NOI18N
        B14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B14ActionPerformed(evt);
            }
        });
        jPanel2.add(B14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 60, 35));

        B11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B11.setName("B11"); // NOI18N
        B11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B11ActionPerformed(evt);
            }
        });
        jPanel2.add(B11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 60, 35));

        B12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B12.setName("B12"); // NOI18N
        B12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B12ActionPerformed(evt);
            }
        });
        jPanel2.add(B12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 60, 35));

        B15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B15.setName("B15"); // NOI18N
        B15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B15ActionPerformed(evt);
            }
        });
        jPanel2.add(B15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 60, 35));

        B02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B02.setName("B02"); // NOI18N
        B02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B02ActionPerformed(evt);
            }
        });
        jPanel2.add(B02, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 60, 35));

        B17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B17.setName("B17"); // NOI18N
        B17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B17ActionPerformed(evt);
            }
        });
        jPanel2.add(B17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 60, 35));

        B18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B18.setName("B18"); // NOI18N
        B18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B18ActionPerformed(evt);
            }
        });
        jPanel2.add(B18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 60, 35));

        B04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B04.setName("B04"); // NOI18N
        B04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B04ActionPerformed(evt);
            }
        });
        jPanel2.add(B04, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 60, 35));

        B05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B05.setName("B05"); // NOI18N
        B05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B05ActionPerformed(evt);
            }
        });
        jPanel2.add(B05, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 60, 35));

        B30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B30.setName("B30"); // NOI18N
        B30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B30ActionPerformed(evt);
            }
        });
        jPanel2.add(B30, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 60, 35));

        B16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B16.setName("B16"); // NOI18N
        B16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B16ActionPerformed(evt);
            }
        });
        jPanel2.add(B16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 60, 35));

        B19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B19.setName("B19"); // NOI18N
        B19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B19ActionPerformed(evt);
            }
        });
        jPanel2.add(B19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 60, 35));

        B29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B29.setName("B29"); // NOI18N
        B29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B29ActionPerformed(evt);
            }
        });
        jPanel2.add(B29, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 60, 35));

        B36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B36.setName("B36"); // NOI18N
        B36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B36ActionPerformed(evt);
            }
        });
        jPanel2.add(B36, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 60, 35));

        B21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B21.setName("B21"); // NOI18N
        B21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B21ActionPerformed(evt);
            }
        });
        jPanel2.add(B21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 60, 35));

        B20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B20.setName("B20"); // NOI18N
        B20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B20ActionPerformed(evt);
            }
        });
        jPanel2.add(B20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 60, 35));

        B22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B22.setName("B22"); // NOI18N
        B22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B22ActionPerformed(evt);
            }
        });
        jPanel2.add(B22, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 60, 35));

        B23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B23.setName("B23"); // NOI18N
        B23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B23ActionPerformed(evt);
            }
        });
        jPanel2.add(B23, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 60, 35));

        B24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B24.setName("B24"); // NOI18N
        B24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B24ActionPerformed(evt);
            }
        });
        jPanel2.add(B24, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 60, 35));

        B25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B25.setName("B25"); // NOI18N
        B25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B25ActionPerformed(evt);
            }
        });
        jPanel2.add(B25, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 60, 35));

        B26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B26.setName("B26"); // NOI18N
        B26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B26ActionPerformed(evt);
            }
        });
        jPanel2.add(B26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 60, 35));

        B27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B27.setName("B27"); // NOI18N
        B27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B27ActionPerformed(evt);
            }
        });
        jPanel2.add(B27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 60, 35));

        B28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B28.setName("B28"); // NOI18N
        B28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B28ActionPerformed(evt);
            }
        });
        jPanel2.add(B28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 60, 35));

        B31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B31.setName("B31"); // NOI18N
        B31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B31ActionPerformed(evt);
            }
        });
        jPanel2.add(B31, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 60, 35));

        B32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B32.setName("B32"); // NOI18N
        B32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B32ActionPerformed(evt);
            }
        });
        jPanel2.add(B32, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 60, 35));

        B33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B33.setName("B33"); // NOI18N
        B33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B33ActionPerformed(evt);
            }
        });
        jPanel2.add(B33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 60, 35));

        B34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B34.setName("B34"); // NOI18N
        B34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B34ActionPerformed(evt);
            }
        });
        jPanel2.add(B34, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 60, 35));

        B35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B35.setName("B35"); // NOI18N
        B35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B35ActionPerformed(evt);
            }
        });
        jPanel2.add(B35, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 60, 35));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Bed01");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Bed02");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Bed03");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Bed04");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Bed06");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Bed05");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Bed07");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Bed08");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Bed09");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Bed10");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Bed11");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Bed12");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Bed13");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Bed14");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Bed15");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Bed16");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Bed17");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Bed18");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Bed19");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Bed20");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Bed22");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Bed21");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Bed23");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Bed25");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Bed26");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Bed27");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Bed28");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Bed31");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Bed32");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, -1, -1));

        B38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B38.setName("B38"); // NOI18N
        B38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B38ActionPerformed(evt);
            }
        });
        jPanel2.add(B38, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 60, 35));

        B37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B37.setName("B37"); // NOI18N
        B37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B37ActionPerformed(evt);
            }
        });
        jPanel2.add(B37, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 60, 35));

        B39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B39.setName("B39"); // NOI18N
        B39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B39ActionPerformed(evt);
            }
        });
        jPanel2.add(B39, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 60, 35));

        B40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/bedgreen.jpg"))); // NOI18N
        B40.setName("B40"); // NOI18N
        B40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B40ActionPerformed(evt);
            }
        });
        jPanel2.add(B40, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, 60, 35));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("Bed33");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("Bed34");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("Bed35");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("Bed36");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("Bed37");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("Bed38");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("Bed39");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("Bed40");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Bed24");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Bed29");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 314, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Bed30");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 314, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Name");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name.setText("name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Location");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        location.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        location.setText("location");
        jPanel1.add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Number of Beds ");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 80, 30));

        nobeds.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nobeds.setText("beds");
        jPanel1.add(nobeds, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover4.jpg"))); // NOI18N
        jLabel42.setText("jLabel42");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 420));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 420));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel44.setText("jLabel44");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 810, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B01ActionPerformed

        new patient(y,"B01").setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_B01ActionPerformed

    private void B07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B07ActionPerformed
        new patient(y,"B07").setVisible(true);
    }//GEN-LAST:event_B07ActionPerformed

    private void B03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B03ActionPerformed
        new patient(y,"B03").setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_B03ActionPerformed

    private void B04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B04ActionPerformed
new patient(y,"B04").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B04ActionPerformed

    private void B05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B05ActionPerformed
new patient(y,"B05").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B05ActionPerformed

    private void B06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B06ActionPerformed
new patient(y,"B06").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B06ActionPerformed

    private void B08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B08ActionPerformed
new patient(y,"B08").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B08ActionPerformed

    private void B09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B09ActionPerformed
new patient(y,"B09").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B09ActionPerformed

    private void B10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B10ActionPerformed
new patient(y,"B10").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B10ActionPerformed

    private void B11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B11ActionPerformed
new patient(y,"B11").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B11ActionPerformed

    private void B12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B12ActionPerformed
new patient(y,"B12").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B12ActionPerformed

    private void B13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B13ActionPerformed
new patient(y,"B13").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B13ActionPerformed

    private void B14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B14ActionPerformed
new patient(y,"B14").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B14ActionPerformed

    private void B15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B15ActionPerformed
new patient(y,"B15").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B15ActionPerformed

    private void B16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B16ActionPerformed
new patient(y,"B16").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B16ActionPerformed

    private void B17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B17ActionPerformed
new patient(y,"B17").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B17ActionPerformed

    private void B18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B18ActionPerformed
new patient(y,"B18").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B18ActionPerformed

    private void B19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B19ActionPerformed
new patient(y,"B19").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B19ActionPerformed

    private void B20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B20ActionPerformed
new patient(y,"B20").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B20ActionPerformed

    private void B21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B21ActionPerformed
new patient(y,"B21").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B21ActionPerformed

    private void B22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B22ActionPerformed
new patient(y,"B22").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B22ActionPerformed

    private void B23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B23ActionPerformed
new patient(y,"B23").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B23ActionPerformed

    private void B24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B24ActionPerformed
new patient(y,"B24").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B24ActionPerformed

    private void B25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B25ActionPerformed
new patient(y,"B25").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B25ActionPerformed

    private void B26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B26ActionPerformed
new patient(y,"B26").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B26ActionPerformed

    private void B27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B27ActionPerformed
new patient(y,"B27").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B27ActionPerformed

    private void B28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B28ActionPerformed
new patient(y,"B28").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B28ActionPerformed

    private void B29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B29ActionPerformed
new patient(y,"B29").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B29ActionPerformed

    private void B30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B30ActionPerformed
new patient(y,"B30").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B30ActionPerformed

    private void B31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B31ActionPerformed
new patient(y,"B31").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B31ActionPerformed

    private void B32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B32ActionPerformed
new patient(y,"B32").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B32ActionPerformed

    private void B33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B33ActionPerformed
new patient(y,"B33").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B33ActionPerformed

    private void B34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B34ActionPerformed
new patient(y,"B34").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B34ActionPerformed

    private void B35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B35ActionPerformed
new patient(y,"B35").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B35ActionPerformed

    private void B02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B02ActionPerformed
       new patient(y,"B02").setVisible(true); 
        // TODO add your handling code here:
    }//GEN-LAST:event_B02ActionPerformed

    private void B36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B36ActionPerformed
new patient(y,"B36").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B36ActionPerformed

    private void B37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B37ActionPerformed
new patient(y,"B37").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B37ActionPerformed

    private void B38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B38ActionPerformed
new patient(y,"B38").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B38ActionPerformed

    private void B39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B39ActionPerformed
new patient(y,"B39").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B39ActionPerformed

    private void B40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B40ActionPerformed
new patient(y,"B40").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_B40ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             try {
            HashMap param=new HashMap();
//param.put("reportParameterName",valueForTheParameter);
staff.MyiReportViewer viewer=new staff.MyiReportViewer("C:\\Users\\X55OL\\Desktop\\reports\\ward.jasper",param);
viewer.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();;
        } 
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B01;
    private javax.swing.JButton B02;
    private javax.swing.JButton B03;
    private javax.swing.JButton B04;
    private javax.swing.JButton B05;
    private javax.swing.JButton B06;
    private javax.swing.JButton B07;
    private javax.swing.JButton B08;
    private javax.swing.JButton B09;
    private javax.swing.JButton B10;
    private javax.swing.JButton B11;
    private javax.swing.JButton B12;
    private javax.swing.JButton B13;
    private javax.swing.JButton B14;
    private javax.swing.JButton B15;
    private javax.swing.JButton B16;
    private javax.swing.JButton B17;
    private javax.swing.JButton B18;
    private javax.swing.JButton B19;
    private javax.swing.JButton B20;
    private javax.swing.JButton B21;
    private javax.swing.JButton B22;
    private javax.swing.JButton B23;
    private javax.swing.JButton B24;
    private javax.swing.JButton B25;
    private javax.swing.JButton B26;
    private javax.swing.JButton B27;
    private javax.swing.JButton B28;
    private javax.swing.JButton B29;
    private javax.swing.JButton B30;
    private javax.swing.JButton B31;
    private javax.swing.JButton B32;
    private javax.swing.JButton B33;
    private javax.swing.JButton B34;
    private javax.swing.JButton B35;
    private javax.swing.JButton B36;
    private javax.swing.JButton B37;
    private javax.swing.JButton B38;
    private javax.swing.JButton B39;
    private javax.swing.JButton B40;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel location;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nobeds;
    // End of variables declaration//GEN-END:variables
}
