/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test2;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Isurunath
 */
public final class ward_property extends javax.swing.JInternalFrame {

    /**
     * Creates new form ward_property
     */
    String Wardno;
    public ward_property() {
        initComponents();
    }
    
    ward_property(String wardno) {
        initComponents();
        Wardno = wardno;
        tabelload1();
        //jLabel1.setText(Wardno);
        tabelload2();
    }
    
    public void tabelload1(){
        
        try{
        
        
        Connection c = DBcon.connect();
        java.sql.Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("SELECT * FROM assign_property where Location='"+Wardno+"'");
        jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
    
    public void tabelload2(){
        
        try{
        
        
        Connection c = DBcon.connect();
        java.sql.Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("SELECT * FROM med_assaign where Location='"+Wardno+"'");
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        search1 = new javax.swing.JTextField();
        searchtype1 = new javax.swing.JComboBox();
        uname = new javax.swing.JLabel();
        yname = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search2 = new javax.swing.JTextField();
        searchtype2 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(900, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setName("Property"); // NOI18N

        jPanel1.setName("Property"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setBackground(new java.awt.Color(204, 204, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PropertyID", "Name", "Quantity", "Status", "Issue Date"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 630, 330));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/update.png"))); // NOI18N
        jButton3.setText("Request");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 130, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/Delete.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 130, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/Search.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 130, -1));
        jPanel1.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 110, -1));

        searchtype1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AID", "Property_name", "Type" }));
        jPanel1.add(searchtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 80, -1));

        uname.setText("jLabel1");
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, -1));

        yname.setText("jLabel1");
        jPanel1.add(yname, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 890, 420));

        jTabbedPane1.addTab("Property", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DrugID", "Name", "Quantity", "ExpireDate"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(375, 64));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 630, 340));
        jPanel3.add(search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 100, -1));

        searchtype2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item_No", "Medicine_Name" }));
        jPanel3.add(searchtype2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 90, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/Search.png"))); // NOI18N
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 120, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/Delete.png"))); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 120, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 890, 420));

        jTabbedPane1.addTab("Medicine", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 890, 420));

        jTabbedPane1.addTab("Blood", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String Search1 = search1.getText();
        String type1= searchtype1.getSelectedItem().toString();

        try {
            Connection c = DBcon.connect();
            java.sql.Statement s=c.createStatement();
            ResultSet rs=s.executeQuery("SELECT * FROM assign_property where "+type1+" LIKE '%"+Search1+"%'");

            // rs = pst.executeQuery();

            jTable2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        int r=jTable2.getSelectedRow();
        String aid=jTable2.getValueAt(r, 0).toString();

        uname.setText(aid);

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try{

            String name = uname.getText();
            Connection c = DBcon.connect();
            java.sql.Statement s = c.createStatement();
            s.executeUpdate("delete from med_assaign where Item_No = '"+name+"'");
            tabelload1();

        } catch(Exception e){

            JOptionPane.showConfirmDialog(null,e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        new propert_request().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int r=jTable1.getSelectedRow();
        String aid=jTable1.getValueAt(r, 0).toString();

        yname.setText(aid);

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        String Search2 = search2.getText();
        String type2= searchtype2.getSelectedItem().toString();

        try {
            Connection c = DBcon.connect();
            java.sql.Statement s=c.createStatement();
            ResultSet rs=s.executeQuery("SELECT * FROM assign_property where "+type2+" LIKE '%"+Search2+"%'");

            // rs = pst.executeQuery();

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try{

            String name = yname.getText();
            Connection c = DBcon.connect();
            java.sql.Statement s = c.createStatement();
            s.executeUpdate("delete from assign_property where AID = '"+name+"'");
            tabelload1();

        } catch(Exception e){

            JOptionPane.showConfirmDialog(null,e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField search1;
    private javax.swing.JTextField search2;
    private javax.swing.JComboBox searchtype1;
    private javax.swing.JComboBox searchtype2;
    private javax.swing.JLabel uname;
    private javax.swing.JLabel yname;
    // End of variables declaration//GEN-END:variables
}
