/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package property;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import test2.DBcon;

/**
 *
 * @author ¬Suranu¬
 */
public class Inventory_handling extends javax.swing.JInternalFrame {
    
    
     Connection c = null;
     PreparedStatement pst =null;
     ResultSet rs = null;
     String Pid;
     String Sid;
     String name;
     String type;
     String quantity;
     String date;
     String warrenty;
     String location;
     String id;

    /**
     * Creates new form Inventory_handling
     */
    public Inventory_handling() throws ClassNotFoundException, SQLException  {
        initComponents();
      
        
        details();
        stableload();
        
    }
     public void stableload()
    {
        try {
            
            c = DBcon.connect();
         
           String sq="SELECT * FROM assign_property ";
          
          pst=c.prepareStatement(sq);
          rs=pst.executeQuery();
          jTable1.setModel(DbUtils.resultSetToTableModel(rs)); 
            
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
       
    }        

     public void details() throws ClassNotFoundException, SQLException{
         
           c = DBcon.connect();
          
          String sq="SELECT * FROM inventoryup ";
          pst=c.prepareStatement(sq);
          rs=pst.executeQuery();
          jTable3.setModel(DbUtils.resultSetToTableModel(rs)); 
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        qtybox = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        locbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        searchType = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(920, 484));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setBackground(new java.awt.Color(204, 204, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PropertyID", "Name", "Quantity", "SupplierID", "IssueDate", "Status", "Location"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 160));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/apply.png"))); // NOI18N
        jButton3.setText("Assign");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 110, 40));
        getContentPane().add(qtybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 90, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Quantity");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));
        getContentPane().add(locbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Location");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/Search.png"))); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 120, -1));
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, 40));

        searchType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SupplierId", "Name", "Type" }));
        getContentPane().add(searchType, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 100, 40));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 850, 150));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/Delete.png"))); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 920, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
             
        
        
        int sum;
        String qty = qtybox.getText();
        sum = (Integer.parseInt(quantity)-Integer.parseInt(qty));
        
        String loc =locbox.getText();
        
        if(sum<0){
            JOptionPane.showMessageDialog(null, "not available");
        }
        else
        {
            int x=JOptionPane.showConfirmDialog(rootPane, "Do you want to assign this record?");
             
            if(x==0){
        try {
            c = DBcon.connect();
            java.sql.Statement s=c.createStatement();
            s.executeUpdate("Insert into assign_property (PropertyId,SupplierId,Name,Type,Quantity,Date,Warrenty,Location) values ('"+Pid+"','"+Sid+"','"+name+"','"+type+"','"+qty+"','"+date+"','"+warrenty+"','"+loc+"')");
            s.executeUpdate("update inventoryup set Quantity = '"+sum+"' where PropertyId = '"+Pid+"' ");
            stableload();
            details();
            
            }
          catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
            }
        }
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String search1 = search.getText();
         String type= searchType.getSelectedItem().toString();
         
         
         try {
            c = DBcon.connect();
            String sql = "SELECT * FROM inventoryup where "+type+" LIKE '%"+search1+"%'";
            pst=c.prepareStatement(sql);
            rs = pst.executeQuery();
            
             jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        int r = jTable3.getSelectedRow();
        
        
         Pid = jTable3.getValueAt(r, 0).toString();
         Sid = jTable3.getValueAt(r, 1).toString();
         name = jTable3.getValueAt(r, 2).toString();
         type = jTable3.getValueAt(r, 3).toString();
         quantity =jTable3.getValueAt(r, 4).toString();
         date = jTable3.getValueAt(r, 5).toString();
         warrenty = jTable3.getValueAt(r, 6).toString();
          location = jTable3.getValueAt(r, 7).toString();
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x=JOptionPane.showConfirmDialog(null, "Do you want to really delete? ");
         
         if(x==0)
         {
             int r = jTable1.getSelectedRow();
             id = jTable1.getValueAt(r, 0).toString();
             
             String sql="DELETE from assign_property where AssignId='"+id+"'";
             
             try {
                  c = DBcon.connect();
              pst=c.prepareStatement(sql);
              pst.execute();
               stableload();
               
              
                
                 
                 
             } catch (Exception e) {
             }
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r = jTable1.getSelectedRow();
        
         id = jTable1.getValueAt(r, 0).toString();
         Pid = jTable1.getValueAt(r, 1).toString();
         Sid = jTable1.getValueAt(r, 2).toString();
         name = jTable1.getValueAt(r, 3).toString();
         type = jTable1.getValueAt(r, 4).toString();
         quantity =jTable1.getValueAt(r, 5).toString();
         date = jTable1.getValueAt(r, 6).toString();
         warrenty = jTable1.getValueAt(r, 7).toString();
          location = jTable1.getValueAt(r, 8).toString();
        
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField locbox;
    private javax.swing.JTextField qtybox;
    private javax.swing.JTextField search;
    private javax.swing.JComboBox searchType;
    // End of variables declaration//GEN-END:variables
}
