/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package property;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import test2.DBcon;

/**
 *
 * @author ¬Suranu¬
 */
public final class request extends javax.swing.JInternalFrame {
    
    Connection c = null;
        PreparedStatement pst =null;
        ResultSet rs = null;
      String Pid;
     String Sid;
     String name;
     String type;
     String quantity;
     String date;
     String warrenty;
     String location;
     String rid;
     String rname;
     String rtype;
     String rloc;
     String rqty;

    /**
     * Creates new form request
     */
    public request() {
        initComponents();
         
     
        tableload();
        stableload();
    }
    
     public void tableload()
    {
        try {
            
            c = DBcon.connect();
            String sql = "SELECT * FROM request";
            pst=c.prepareStatement(sql);
            rs = pst.executeQuery();
             
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
       
    }
     
      public void stableload()
    {
        try {
            
              c = DBcon.connect();
          
          String sq="SELECT * FROM inventoryup ";
          pst=c.prepareStatement(sq);
          rs=pst.executeQuery();
          jTable2.setModel(DbUtils.resultSetToTableModel(rs)); 
            
        } catch (Exception e) {
        }
       
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        locbox = new javax.swing.JTextField();
        qtybox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(920, 484));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 810, 170));

        jTable2.setBackground(new java.awt.Color(204, 204, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 820, 150));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/apply.png"))); // NOI18N
        jButton1.setText("ASSIGN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 130, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Location");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 60, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Quantity");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        locbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locboxActionPerformed(evt);
            }
        });
        getContentPane().add(locbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 80, 30));
        getContentPane().add(qtybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Property_Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 110, -1));
        getContentPane().add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 100, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 920, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        int sum;
        String qty = qtybox.getText();
        sum = (Integer.parseInt(quantity)-Integer.parseInt(qty));
        
        String name1=namebox.getText();
        String loc =locbox.getText();
        
        if(sum<0){
            JOptionPane.showMessageDialog(null, "not available");
        }
        
        
        
        else
        {
            int x=JOptionPane.showConfirmDialog(rootPane, "Do you want to assign this record?");
             
            if(x==0){
        try {
            c = DBcon.connect();
            java.sql.Statement s=c.createStatement();
            s.executeUpdate("Insert into assign_property (PropertyId,SupplierId,Name,Type,Quantity,Date,Warrenty,Location) values ('"+Pid+"','"+Sid+"','"+name+"','"+type+"','"+qty+"','"+date+"','"+warrenty+"','"+loc+"')");
            s.executeUpdate("update inventoryup set Quantity = '"+sum+"' where PropertyId = '"+Pid+"' ");
             s.executeUpdate("DELETE from request where Property_Name='"+name1+"'  AND  Quantity='"+qty+"' AND Location='"+loc+"'");
           
             
             
              
             // pst=c.prepareStatement(sql);
              //pst.execute();
            stableload();
            tableload();
            
            
        }
          catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r = jTable2.getSelectedRow();
        rid = jTable2.getValueAt(r, 0).toString();
         rname = jTable2.getValueAt(r, 1).toString();
         rtype = jTable2.getValueAt(r, 2).toString();
          rqty = jTable2.getValueAt(r, 2).toString();
           rloc = jTable2.getValueAt(r, 2).toString();
         
    }//GEN-LAST:event_jTable1MouseClicked

    private void locboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locboxActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int r = jTable2.getSelectedRow();
        Pid = jTable2.getValueAt(r, 0).toString();
         Sid = jTable2.getValueAt(r, 1).toString();
         name = jTable2.getValueAt(r, 2).toString();
         type = jTable2.getValueAt(r, 3).toString();
         quantity =jTable2.getValueAt(r, 4).toString();
         date = jTable2.getValueAt(r, 5).toString();
         warrenty = jTable2.getValueAt(r, 6).toString();
          location = jTable2.getValueAt(r, 7).toString();
    }//GEN-LAST:event_jTable2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField locbox;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField qtybox;
    // End of variables declaration//GEN-END:variables
}
