/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package property;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import test2.DBcon;

/**
 *
 * @author ¬Suranu¬
 */
public final class Supplier extends javax.swing.JInternalFrame {
    
     Connection c = null;
     PreparedStatement pst =null;
     ResultSet rs = null;
    

    /** Creates new form Supplier */
    public Supplier() {
        initComponents();
        stableload();
        
    }
    
    
     public void stableload()
    {
        try {
            
            c = DBcon.connect();
            String sql = "SELECT SupplierId,SupplierName,Company,Type,Address,Contact,Email FROM supplier";
            pst=c.prepareStatement(sql);
            rs = pst.executeQuery();
             
            table1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
       
    }        
    

    /** This method is called from within the constructor to
     *  the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        namebox1 = new javax.swing.JTextField();
        combox1 = new javax.swing.JTextField();
        typebox1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        addbox1 = new javax.swing.JTextField();
        conbox1 = new javax.swing.JTextField();
        emailbox1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        searchType = new javax.swing.JComboBox();
        search = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(920, 484));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Suplier"));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Name");
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Company");
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Property Type");
        jPanel10.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        namebox1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.add(namebox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 120, -1));

        combox1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.add(combox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 120, -1));

        typebox1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.add(typebox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 120, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Address");
        jPanel10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Contact");
        jPanel10.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        addbox1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.add(addbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 100, -1));

        conbox1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.add(conbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 100, -1));

        emailbox1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.add(emailbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 100, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Email");
        jPanel10.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/add.png"))); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 100, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 40, -1));

        jLabel2.setText("Id");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 90, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover3.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 780, 150));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 800, 180));

        searchType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SupplierName", "Company", "Type", "Address", "Contact", "Email" }));
        getContentPane().add(searchType, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 120, 40));
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 120, 40));

        table1.setBackground(new java.awt.Color(204, 204, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(table1);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 820, 170));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/Search.png"))); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 120, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/update.png"))); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 120, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/Delete.png"))); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 920, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(!namebox1.getText().toString().equals("")&&!combox1.getText().toString().equals("")&&!typebox1.getText().toString().equals("")&&!addbox1.getText().toString().equals("")&&!conbox1.getText().toString().equals("")&&!emailbox1.getText().toString().equals(""))
{
    String pattern="[0-9]+";
     String pattern1="[a-zA-Z ]+";
     
     
     
     
    
    String EMAIL_REGEX = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
                String email = emailbox1.getText();
                if(email.matches(EMAIL_REGEX))
                {
                    String con = conbox1.getText();
            if(con.length()==10 && con.matches(pattern) )
            {
                 String name = namebox1.getText();
                 if(!namebox1.getText().equals("") && name.matches(pattern1))
                 {
    
         int x=JOptionPane.showConfirmDialog(rootPane, "Do you want to add this record?");
            if(x==0){
      
        String company = combox1.getText();
        String type = typebox1.getText();
        String add = addbox1.getText();
       
        

        try {
            c = DBcon.connect();
            java.sql.Statement s=c.createStatement();
            s.executeUpdate("Insert into supplier (SupplierName,Company,Type,Address,Contact,Email) values ('"+name+"','"+company+"','"+type+"','"+add+"','"+con+"','"+email+"')");
            stableload();
            
                jLabel2.setText("");
                namebox1.setText("");
                combox1.setText("");
                typebox1.setText("");
                addbox1.setText("");
                conbox1.setText("");
                emailbox1.setText("");
                      
                
              
         
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "This Record is already exists","",JOptionPane.ERROR_MESSAGE);
        }
            }
            
            else if(x==1){
                namebox1.setText("");
                combox1.setText("");
                typebox1.setText("");
                addbox1.setText("");
                conbox1.setText("");
                emailbox1.setText("");
                jLabel2.setText("");
                
            }

            else if(x==2){
                namebox1.setText("");
                combox1.setText("");
                typebox1.setText("");
                addbox1.setText("");
                conbox1.setText("");
                emailbox1.setText("");
                jLabel2.setText("");
            }
                 }
                 else
                {
                    JOptionPane.showMessageDialog(null, "Invalid Name Details","",JOptionPane.ERROR_MESSAGE);
                }
            }
            
            
            else
                {
                    JOptionPane.showMessageDialog(null, "Invalid contact number Details","",JOptionPane.ERROR_MESSAGE);
                }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Invalid Email Details","",JOptionPane.ERROR_MESSAGE);
                }
}
else
        {
            JOptionPane.showMessageDialog(null, "Enter Essential Details","",JOptionPane.ERROR_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String search1 = search.getText();
         String type= searchType.getSelectedItem().toString();
         
         try {
            c = DBcon.connect();
            String sql = "SELECT * FROM supplier where "+type+" LIKE '%"+search1+"%'";
            pst=c.prepareStatement(sql);
            rs = pst.executeQuery();
            
            table1.setModel(DbUtils.resultSetToTableModel(rs));
            
            search.setText("");
            
        } catch (Exception e) {
        }
            


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int x=JOptionPane.showConfirmDialog(null, "Do you want to really update? ");
        
        if(x==0)
        {
                String id=jLabel2.getText();
                String name=namebox1.getText();
                String company=combox1.getText();
                String type=typebox1.getText();
                String address=addbox1.getText();
                String contact=conbox1.getText();
                String email=emailbox1.getText();
                
                
                 
                String sql=" UPDATE supplier SET SupplierName= '"+name+"',Company= '"+company+"',Type= '"+type+"',Address= '"+address+"',Contact= '"+contact+"',Email='"+email+"' where SupplierId= '"+id+"'";
              try {
                 c = DBcon.connect();
                pst=c.prepareStatement(sql);
                pst.execute();
                 stableload();
                
                 namebox1.setText("");
                combox1.setText("");
                typebox1.setText("");
                addbox1.setText("");
                conbox1.setText("");
                emailbox1.setText("");
                jLabel2.setText("");
                
                
                
            } catch (Exception e) {
            }
        }
        
        else if(x==1){
                namebox1.setText("");
                combox1.setText("");
                typebox1.setText("");
                addbox1.setText("");
                conbox1.setText("");
                emailbox1.setText("");
                jLabel2.setText("");
            }

            else if(x==2){
                namebox1.setText("");
                combox1.setText("");
                typebox1.setText("");
                addbox1.setText("");
                conbox1.setText("");
                emailbox1.setText("");
                jLabel2.setText("");
            }
            
            
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
         int x=JOptionPane.showConfirmDialog(null, "Do you want to really delete? ");
         
         if(x==0)
         {
             String id= jLabel2.getText();
             
             String sql="DELETE from supplier where SupplierId='"+id+"'";
             
             try {
                  c = DBcon.connect();
              pst=c.prepareStatement(sql);
              pst.execute();
               stableload();
               
                namebox1.setText("");
                combox1.setText("");
                typebox1.setText("");
                addbox1.setText("");
                conbox1.setText("");
                emailbox1.setText("");
                jLabel2.setText("");
                
                 
                 
             } catch (Exception e) {
             }
         }
         
         else if(x==1){
                namebox1.setText("");
                combox1.setText("");
                typebox1.setText("");
                addbox1.setText("");
                conbox1.setText("");
                emailbox1.setText("");
                jLabel2.setText("");
            }

            else if(x==2){
                namebox1.setText("");
                combox1.setText("");
                typebox1.setText("");
                addbox1.setText("");
                conbox1.setText("");
                emailbox1.setText("");
                jLabel2.setText("");
            }
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        int r = table1.getSelectedRow();
        
        String id = table1.getValueAt(r, 0).toString();
        String name = table1.getValueAt(r, 1).toString();
        String company = table1.getValueAt(r, 2).toString();
        String type = table1.getValueAt(r, 3).toString();
        String address = table1.getValueAt(r, 4).toString();
        String contact = table1.getValueAt(r, 5).toString();
        String email = table1.getValueAt(r, 6).toString();
        
        
        namebox1.setText(name);
        combox1.setText(company);
        typebox1.setText(type);
        addbox1.setText(address);
        conbox1.setText(contact);
        emailbox1.setText(email);
        jLabel2.setText(id);
    }//GEN-LAST:event_table1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addbox1;
    private javax.swing.JTextField combox1;
    private javax.swing.JTextField conbox1;
    private javax.swing.JTextField emailbox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField namebox1;
    private javax.swing.JTextField search;
    private javax.swing.JComboBox searchType;
    private javax.swing.JTable table1;
    private javax.swing.JTextField typebox1;
    // End of variables declaration//GEN-END:variables

}
