/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ambulance;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author X55OL
 */
public final class bbb extends javax.swing.JFrame {
    
    Connection c= null;
    PreparedStatement p=null;
    ResultSet rs=null;
    String name;
    
    
    /**
     * Creates new form ab
     */
    public bbb() {
        initComponents();
        tableload();
        tableload2();
        tableload3();
        tableload4();
        tableload5();
        tableload6();
            
    }
    
    public void tableload6(){
        
        try {
            c = DB.mycon();
            String sql="SELECT p.pid,p.name,p.gender,p.blood from hospital_transfer t,p2 p where t.patientID = p.pid";
            
          PreparedStatement x=c.prepareStatement(sql);
          ResultSet s=x.executeQuery();
          jTable6.setModel(DbUtils.resultSetToTableModel(s));
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(rootPane, "error");
        }
    }
    
    
     public void tableload(){
        try {
           // Connection d = DB.mycon();
            c = DB.mycon();
           // String sql=" SELECT id1, name,address,tp,id,username,password from register WHERE name='"+txtname.getText()+"' ";
            String sql="SELECT * from drive";
            
            
          PreparedStatement x=c.prepareStatement(sql);
          ResultSet s=x.executeQuery();
          jTable7.setModel(DbUtils.resultSetToTableModel(s));
            
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        }
        
    }
      public void tableload2(){
        try {
             c=DB.mycon();
           
            String sql="SELECT * from vehi";
            
            
           p=c.prepareStatement(sql);
            rs=p.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        } catch (Exception e) {
        e.printStackTrace();
        }
        
    }
       public void tableload3(){
        try {
             c=DB.mycon();
          
            String sql="SELECT * from transfer";
            
            
           p=c.prepareStatement(sql);
            rs=p.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        } catch (Exception e) {
        e.printStackTrace();
        }
       }
     public void tableload4(){
        try {
             c=DB.mycon();
           // String sql=" SELECT id1, name,address,tp,id,username,password from register WHERE name='"+txtname.getText()+"' ";
            String sql="SELECT * from vehi";
            
            
           p=c.prepareStatement(sql);
            rs=p.executeQuery();
            jTable4.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        } catch (Exception e) {
        e.printStackTrace();
        }
        
    }
 public void tableload5(){
        try {
             c=DB.mycon();
           // String sql=" SELECT id1, name,address,tp,id,username,password from register WHERE name='"+txtname.getText()+"' ";
            String sql="SELECT * from drive";
            
            
           p=c.prepareStatement(sql);
            rs=p.executeQuery();
            jTable5.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        } catch (Exception e) {
        e.printStackTrace();
        }
 }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jButton13 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField13 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jButton18 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField8 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/15106-illustration-of-a-red-close-button-pv.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 30, 30));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Assing");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 75, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehicle"));

        jTable4.setBackground(new java.awt.Color(204, 204, 255));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 360, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Driver's details"));

        jTable5.setBackground(new java.awt.Color(204, 204, 255));
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 360, 140));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient's detail"));

        jTable6.setBackground(new java.awt.Color(204, 204, 255));
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable6MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable6);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, 140));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Transfer's Details"));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Vehicle ID");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 52, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Drive ID");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 83, 47, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Patient ID");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 114, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("nurse ID");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 145, 54, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Destination");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 80, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Date");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 60, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Hours");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 50, -1));

        jTextField18.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 115, -1));

        jTextField16.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 115, -1));

        jComboBox4.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Angoda", "Dabhana", "Puthukuduiruppu" }));
        jPanel10.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 115, -1));

        jTextField13.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 117, -1));

        jTextField12.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 117, -1));

        jTextField11.setBackground(new java.awt.Color(204, 204, 255));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 117, -1));

        jTextField10.setBackground(new java.awt.Color(204, 204, 255));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 117, -1));

        jButton14.setText("D");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 40, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover3.jpg"))); // NOI18N
        jLabel22.setText("jLabel22");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 510, 190));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 510, 210));

        jButton17.setText("Update");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jTable3.setBackground(new java.awt.Color(204, 204, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 500, 180));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel20.setText("jLabel20");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 920, -1));

        jTabbedPane1.addTab("Transfer Management", jPanel4);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 70, -1));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 70, -1));

        jButton10.setText("View Profile");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Driver's Details"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 35, 113, -1));

        jTextField5.setBackground(new java.awt.Color(204, 204, 255));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 73, 113, -1));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 464, 103, -1));

        jLabel7.setText("Lincence No");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 467, 66, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 76, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NIC");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 38, 33, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 33, 32, -1));

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 135, -1));

        jTextField2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 134, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 59, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 90, -1, -1));

        jTextField3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 135, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 154, -1, -1));

        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 135, 71));

        jLabel24.setText("Date");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 499, -1, -1));

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 496, 103, -1));

        jButton15.setText("D");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 495, 56, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Licen Number");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 114, 85, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Date");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 153, -1, -1));

        jTextField15.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 111, 113, -1));

        jTextField20.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 150, 113, -1));

        jButton16.setText("Date");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 149, -1, -1));

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 149, 87, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover3.jpg"))); // NOI18N
        jLabel29.setText("jLabel29");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 800, 220));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 800, 240));

        jButton12.setText("Clear");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel25.setText("jLabel25");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1301, 66, -1, -1));

        jTable7.setBackground(new java.awt.Color(204, 204, 255));
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable7MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jTable7);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 800, 140));

        jButton18.setText("Report");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel32.setText("jLabel28");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 490));

        jLabel28.setText("jLabel28");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        jTabbedPane1.addTab("Drive Management", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setBackground(new java.awt.Color(204, 204, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 790, 150));

        jButton6.setText("ADD");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 60, -1));

        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 80, -1));

        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehicle Details"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Type");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Insurance No");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fuel Type");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jComboBox3.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select type", "petrol", "dieasel", " " }));
        jPanel5.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jTextField8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 81, -1));

        jComboBox2.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Type", "A/C", "Non A/C" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jTextField7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 81, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Chassis No");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jTextField9.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 81, -1));

        jComboBox1.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Type", "Auto ", "Manual" }));
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Gear Type");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Reg Date");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jTextField14.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 80, -1));

        jButton11.setText("Date");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 70, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover3.jpg"))); // NOI18N
        jLabel31.setText("jLabel29");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 790, 180));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 790, 200));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel33.setText("jLabel28");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 490));

        jTabbedPane1.addTab("Vehicle Management", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 910, 520));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/logo2.jpg"))); // NOI18N
        jLabel34.setText("jLabel5");
        jLabel34.setPreferredSize(new java.awt.Dimension(940, 110));
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                String id=jTextField7.getText();
                String type=jComboBox2.getSelectedItem().toString();
                String insuno=jTextField8.getText();
                String fueltype=jComboBox3.getSelectedItem().toString();
                String chassisno=jTextField9.getText();
                String gear=jComboBox4.getSelectedItem().toString();  
                String reg= jTextField14.getText();
        try {
             c=DB.mycon();
            Statement s=c.createStatement();
            s.executeUpdate ("UPDATE vehi SET  Type='"+type+"',Insurance_Number='"+insuno+"',Fuel_Type='"+fueltype+"',Chassis_Number='"+chassisno+"',Gear='"+gear+"',Date='"+reg+"' WHERE Vehicle_ID='"+id+"'" );
            //   String sql=" SELECT id1, name,address,tp,id,username,password from register WHERE name='"+txtname.getText()+"' ";
            //   p=c.prepareStatement(sql);
            //^rs=p.executeQuery();
            //  table.setModel(DbUtils.resultSetToTableModel(rs));
            tableload2();
        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
if(!jTextField7.getText().toString().equals("")&&!jTextField8.getText().toString().equals("")&&!jTextField9.getText().toString().equals("")&&!jTextField14.getText().toString().equals("")){
        try{
            int x=JOptionPane.showConfirmDialog(rootPane,"DO YOU WANT TO Add?????");
            if (x==0){
                c =DB.mycon();

                // Connection c=DB.mycon();
                Statement s=c.createStatement();

                String id=jTextField7.getText();
                String type=jComboBox2.getSelectedItem().toString();
                String insuno=jTextField8.getText();
                String fueltype=jComboBox3.getSelectedItem().toString();
                String chassisno=jTextField9.getText();
                String gear=jComboBox1.getSelectedItem().toString();
                String reg= jTextField14.getText();

                s.executeUpdate("INSERT INTO vehi (Vehicle_ID,Type,Insurance_Number,Fuel_Type, Chassis_Number, Gear,Date) VALUES ('"+id+"','"+type+"','"+insuno+"','"+fueltype+"','"+chassisno+"','"+gear+"','"+reg+"')");
                tableload2();

                jTextField7.setText(" ");
                jTextField8.setText(" ");
                jComboBox2.setSelectedIndex(0);
                jComboBox3.setSelectedIndex(0);
                jTextField9.setText(" ");
                jComboBox1.setSelectedIndex(0);
                jTextField14.setText(" ");

            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
}
      else
        {
            JOptionPane.showMessageDialog(null, "Enter Essential Details","",JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                jTextField10.setText(" ");
                jTextField11.setText(" ");
                jTextField12.setText(" ");
                jComboBox4.setSelectedIndex(0);
                jTextField13.setText(" ");
                jTextField16.setText(" ");
               
                jTextField18.setText(" ");  
                        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
             c=DB.mycon();

            // Connection c=DB.mycon();
            Statement s=c.createStatement();
            ResultSet rs=s.executeQuery("SELECT *FROM drive WHERE name='"+jTextField1.getText()+"'");
            while(rs.next()){
                jTextField2.setText(rs.getString("age"));
                jTextField3.setText(rs.getString("lastname"));
                jTextArea1.setText(rs.getString("address"));
                jTextField4.setText(rs.getString("nic"));
                jTextField5.setText(rs.getString("pnumber"));
                jTextField6.setText(rs.getString("linum"));
                
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name=jTextField1.getText();
                String fname=jTextField2.getText();
                String address=jTextArea1.getText();
                String lname=jTextField3.getText();
                String nic=jTextField4.getText();
                String pnumber=jTextField5.getText();
                String linum=jTextField15.getText();
                String date=jTextField20.getText();
                
        try {
            Connection c=DB.mycon();
            Statement s=c.createStatement();
            s.executeUpdate ("UPDATE drive SET  First_Name='"+fname+"',Address='"+address+"',Last_Name='"+lname+"',National_Identy='"+nic+"',Phone_Number='"+pnumber+"',Lincense_number='"+linum+"',Date='"+date+"' WHERE Driver_ID='"+jTextField1.getText()+"'" );
            //   String sql=" SELECT id1, name,address,tp,id,username,password from register WHERE name='"+txtname.getText()+"' ";
            //   p=c.prepareStatement(sql);
            //^rs=p.executeQuery();
            //  table.setModel(DbUtils.resultSetToTableModel(rs));
            tableload();
        } catch (Exception e) {
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(!jTextField1.getText().toString().equals("")&&!jTextField2.getText().toString().equals(""))
{       
    String pattern="[0-9]+";
     String pattern1="[a-zA-Z ]+";
       String pnumber = jTextField5.getText();
       if(pnumber.length()==10 && pnumber.matches(pattern) )
       {
            
            String nic=jTextField4.getText();
            if(nic.length()==10 &&nic.charAt(9)=='V')
            {
                 //JFileChooser chooser =new JFileChooser();
               //File f =chooser.getSelectedFile();
       // String path=f.getAbsolutePath();
       // path=path.replace("\\","/");
        
    
                       name=jTextField1.getText();
                String fname=jTextField2.getText();
                String address=jTextArea1.getText();
                String lname=jTextField3.getText();
                
                
                String linum=jTextField15.getText();
                
                String date=jTextField20.getText();
    
    try{
            int x=JOptionPane.showConfirmDialog(rootPane,"DO YOU WANT TO ADD?????");
            if (x==0){
                 c =DB.mycon();
                Statement s=c.createStatement();

                

                // s.executeUpdate("INSERT INTO ish (name,age,address,lastname,pnumber,linum) values ('"+jTextField1.getText()+"','"+jTextField2.getText()+"','"+jTextArea1.getText()+"','"+jTextField3.getText()+"','"+jTextField5.getText()+"')");

                s.executeUpdate("INSERT INTO drive (Driver_ID,First_Name,Last_Name,Address,National_Identy,Phone_Number,Lincense_Number,Date) VALUES ('"+name+"','"+fname+"','"+lname+"','"+address+"','"+nic+"','"+pnumber+"','"+linum+"','"+date+"')");
                tableload();
                JOptionPane.showMessageDialog(null, " Driver Details Registration Successfull","",JOptionPane.INFORMATION_MESSAGE);

                jTextField1.setText(" ");
                jTextField2.setText(" ");
                jTextArea1.setText(" ");
                jTextField3.setText(" ");
                jTextField4.setText(" ");
                jTextField5.setText(" ");
                jTextField6.setText(" ");
                jTextField19.setText("");
                jTextField15.setText("");
                jTextField20.setText("");                
            }

        }
        catch(Exception e){
          //  e.printStackTrace();
                            JOptionPane.showMessageDialog(null, "Duplicate NIC Details","",JOptionPane.ERROR_MESSAGE);

        }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid NIC Details","",JOptionPane.ERROR_MESSAGE);
            }
            
}   
              else
        {
            JOptionPane.showMessageDialog(null, "Error phone number","",JOptionPane.ERROR_MESSAGE);
        }
}
       else
        {
            JOptionPane.showMessageDialog(null, "Enter Essential Details","",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            int x=JOptionPane.showConfirmDialog(rootPane,"DO YOU WANT TO DELETE?????");

            if (x==0){
                 c =DB.mycon();

                Statement s=c.createStatement();

                s.executeUpdate("DELETE FROM drive WHERE Driver_ID='"+jTextField1.getText()+"' ");
                tableload();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed
   }                                        
  catch (Exception e) {
    e.printStackTrace();
    }
    }
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      try {
            int x=JOptionPane.showConfirmDialog(rootPane,"DO YOU WANT TO DELETE?????");

            if (x==0){
                 c =DB.mycon();

                Statement s=c.createStatement();

                s.executeUpdate("DELETE FROM vehi WHERE Vehicle_ID='"+jTextField7.getText()+"' ");
                tableload2();        // TODO add your handling code here:
    }                                        
   }                                        
  catch (Exception e) {
    e.printStackTrace();
    }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if(!jTextField10.getText().toString().equals("")&&!jTextField11.getText().toString().equals("")&&!jTextField12.getText().toString().equals("")&&!jTextField13.getText().toString().equals("")&&!jTextField16.getText().toString().equals("")&&!jTextField18.getText().toString().equals("")){
       try{
            int x=JOptionPane.showConfirmDialog(rootPane,"DO YOU WANT TO Add?????");
            if (x==0){
                 c =DB.mycon();

                // Connection c=DB.mycon();
                Statement s=c.createStatement();

                String vehiid=jTextField10.getText();
                String driveid=jTextField11.getText();
                String patid=jTextField12.getText();
                String nurid=jTextField13.getText();
                String des=jComboBox4.getSelectedItem().toString();
                String date=jTextField16.getText();
                
                String hour=jTextField18.getText();
                

                s.executeUpdate("INSERT INTO transfer (Vehicle_ID,Driver_ID,Patient_ID,Nurse_ID,Destination,Date,hours) VALUES ('"+vehiid+"','"+driveid+"','"+patid+"','"+nurid+"','"+des+"','"+date+"','"+hour+"')");
                tableload3();

                 jTextField10.setText(" ");
                jTextField11.setText(" ");
                
                jTextField12.setText(" ");
                jTextField13.setText(" ");
                jTextField5.setText(" ");
                jTextField16.setText(" ");
                
                jTextField18.setText("");
              

            }

        }
        catch(Exception e){
            e.printStackTrace();

        } 
}
       else
        {
            JOptionPane.showMessageDialog(null, "Enter Transfer Details","",JOptionPane.ERROR_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        new Profile(name).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
 int rs=jTable2.getSelectedRow();
       String vehid=jTable2.getValueAt(rs,0).toString();
       String type=jTable2.getValueAt(rs,1).toString();
       String insuno=jTable2.getValueAt(rs, 2).toString();
       String fueltype=jTable2.getValueAt(rs, 3).toString();
       String chassisno=jTable2.getValueAt(rs,4).toString();
       String gear=jTable2.getValueAt(rs, 5).toString();
         String reg=jTable2.getValueAt(rs, 6).toString();
       
       

        jTextField7.setText(vehid);
        jTextField8.setText(insuno);
        jTextField9.setText(chassisno);
        jComboBox1.setSelectedItem(gear);
        jComboBox2.setSelectedItem(type);
        jComboBox3.setSelectedItem(fueltype);
        jTextField14.setText(reg);
              // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        DatePicker Dp=new DatePicker(this);
        jTextField14.setText(Dp.setPickedDate());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
                jTextField1.setText(" ");
                jTextField2.setText(" ");
                jTextArea1.setText(" ");
                jTextField3.setText(" ");
                jTextField4.setText(" ");
                jTextField5.setText(" ");
                jTextField6.setText(" ");  
                 jTextField15.setText(" ");
                  jTextField20.setText(" ");  
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
DatePicker Dp=new DatePicker(this);
jTextField16.setText(Dp.setPickedDate());      
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
DatePicker Dp=new DatePicker(this);
jTextField19.setText(Dp.setPickedDate());          
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
 DatePicker Dp=new DatePicker(this);
        jTextField20.setText(Dp.setPickedDate());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jTable7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable7MouseClicked
        int rs=jTable7.getSelectedRow();
       String id=jTable7.getValueAt(rs,0).toString();
       String fname=jTable7.getValueAt(rs,1).toString();
       String lname=jTable7.getValueAt(rs, 2).toString();
       String address=jTable7.getValueAt(rs, 3).toString();
       String nic=jTable7.getValueAt(rs,4).toString();
       String pnumber=jTable7.getValueAt(rs, 5).toString();
       String linum=jTable7.getValueAt(rs, 6).toString();
       String date=jTable7.getValueAt(rs, 7).toString();
       

        jTextField1.setText(id);
        jTextField2.setText(fname);
        jTextField3.setText(lname);
        jTextArea1.setText(address);
        jTextField4.setText(nic);
        jTextField5.setText(pnumber);
        
        jTextField15.setText(linum);
        jTextField20.setText(date);
        
      
    }//GEN-LAST:event_jTable7MouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
 String vehiid=jTextField10.getText();
                String driveid=jTextField11.getText();
                String patid=jTextField12.getText();
                String nurid=jTextField13.getText();
                String des=jComboBox4.getSelectedItem().toString();
                String date=jTextField16.getText();
                
                String hour=jTextField18.getText();     
        try {
             c=DB.mycon();
            Statement s=c.createStatement();
            s.executeUpdate ("UPDATE transfer SET  driveid='"+driveid+"',patid='"+patid+"',nurid='"+nurid+"',destination='"+des+"',date='"+date+"',hours='"+hour+"' WHERE vedid='"+vehiid+"'" );
            //   String sql=" SELECT id1, name,address,tp,id,username,password from register WHERE name='"+txtname.getText()+"' ";
            //   p=c.prepareStatement(sql);
            //^rs=p.executeQuery();
            //  table.setModel(DbUtils.resultSetToTableModel(rs));
            tableload3();
        } catch (Exception e) {
            e.printStackTrace();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        int rs=jTable3.getSelectedRow();
        String vehid=jTable3.getValueAt(rs,0).toString();
        String drid=jTable3.getValueAt(rs,1).toString();
        String patid=jTable3.getValueAt(rs, 2).toString();
        String nurid=jTable3.getValueAt(rs, 3).toString();
        String des=jTable3.getValueAt(rs,4).toString();
        String date=jTable3.getValueAt(rs, 5).toString();
        
        String hour=jTable3.getValueAt(rs, 6).toString();

        jTextField10.setText(vehid);
        jTextField11.setText(drid);
        jTextField12.setText(patid);
        jTextField13.setText(nurid);
        jComboBox4.setSelectedItem(des);
        jTextField16.setText(date);
        
        jTextField18.setText(hour);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
int rs=jTable4.getSelectedRow();
       String vehid=jTable4.getValueAt(rs,0).toString(); 
       jTextField10.setText(vehid);
    }//GEN-LAST:event_jTable4MouseClicked

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
 int rs=jTable5.getSelectedRow();
       String id=jTable5.getValueAt(rs,0).toString();  
       jTextField11.setText(id);// TODO add your handling code here:
    }//GEN-LAST:event_jTable5MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTable6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable6MouseClicked
      int rs=jTable6.getSelectedRow();
       String pid =jTable6.getValueAt(rs,0).toString(); 
       jTextField12.setText(pid);  // TODO add your handling code here:
    }//GEN-LAST:event_jTable6MouseClicked

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
     try {
            HashMap param=new HashMap();
//param.put("reportParameterName",valueForTheParameter);
staff.MyiReportViewer viewer=new staff.MyiReportViewer("C:\\Users\\X55OL\\Desktop\\reports\\ambulance.jasper",param);
viewer.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();;
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bbb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bbb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bbb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bbb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bbb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
