/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package staff;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Deerasinghe
 */
public final class addLeave extends javax.swing.JFrame {
    
     Connection c = null;
    PreparedStatement pst=null;
    ResultSet rs = null;
    
  private String ppid;
    


    /**
     * Creates new form addLeave
     * 
     * 
     */
      
   String uname;
    public addLeave()  throws ClassNotFoundException, SQLException {
        initComponents();
        c = DB.mycon();
      
    }
    
      
    public addLeave(String ppid)
    {
             initComponents();
       // ppid=id;
        txtid.setText(ppid);
        
          
       
        cbtype.setSelectedIndex(0);
      
        txtbegin.setText("");
        txtend.setText("");
        txtpurpose.setText("");
     
        Calendar javaCalendar = null;
        String currentDate = "";

        javaCalendar = Calendar.getInstance();

        currentDate = javaCalendar.get(Calendar.DATE) + "/" + (javaCalendar.get(Calendar.MONTH) + 1) + "/" + javaCalendar.get(Calendar.YEAR);
        txtdate.setText(currentDate);

        
        details();
    
    }
   

        public void details() {
        //  String us = jLabel9.getText().toString();
       //txtempid.setText(uss);
            
            try {
                
                String sql = "SELECT * from employee WHERE Employee_Id= '"+txtid+"'";
            pst=c.prepareStatement(sql);
          rs = pst.executeQuery();
           
           while(rs.next())
           {
           txtid.setText(rs.getString("Employee ID"));
           }
                
            } catch (Exception e) {
           }
          
      }
        
        
        
        
     //   public void table3() throws SQLException{
         
       // String Id =  txtid.getText().toString();;
       // String sql = "select * from emp_leave where Employee_Id='"+Id+"'";
       // pst = c.prepareStatement(sql);
       // rs = pst.executeQuery();
       
         // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
   // }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        txtid = new javax.swing.JLabel();
        cbtype = new javax.swing.JComboBox();
        txtdate = new javax.swing.JLabel();
        txtpurpose = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtbegin = new javax.swing.JLabel();
        txtend = new javax.swing.JLabel();
        txtduration = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtid.setText("EmployeeId");
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 80, 20));

        cbtype.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select one", "annual leave", "casual leave", "sick leave", "vacation leave" }));
        getContentPane().add(cbtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, 30));

        txtdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdate.setText("Date");
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 80, -1));
        getContentPane().add(txtpurpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 200, 60));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/apply.png"))); // NOI18N
        jButton1.setText("APPLY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 120, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/cancel.png"))); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 120, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Employee ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Leave Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Leave Begin");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Leave End");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 100, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Purpose");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 80, 20));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/calender.png"))); // NOI18N
        jButton3.setText("Calender");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 130, 20));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/calender.png"))); // NOI18N
        jButton4.setText("Calender");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Duration of Leave");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 120, 20));

        txtbegin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtbegin.setText("begin date");
        getContentPane().add(txtbegin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 90, 20));

        txtend.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtend.setText("end date");
        getContentPane().add(txtend, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 90, 20));

        txtduration.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtduration.setText("duration");
        getContentPane().add(txtduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 60, 20));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 640, 100));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/logo2.jpg"))); // NOI18N
        jLabel9.setText("jLabel5");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 690, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 690, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       try {                                        
      
    int x=JOptionPane.showConfirmDialog(rootPane, "Do you want to apply this record?");
       if(x==0){
          
          
            
                 
            
       String id= txtid.getText();
       String type= cbtype.getSelectedItem().toString();
       String date=txtdate.getText();
       String begin= txtbegin.getText();
       String end= txtend.getText();
       String pur= txtpurpose.getText();
       String duration=txtduration.getText();
    // String sta=txtstatus.getText();
       String com= "s";
       String pen = "Pending";
       
       
//      DateFormat df = new SimpleDateFormat("yyyy-MM-dd");   //get current date for validation
//       Calendar cal = Calendar.getInstance();
//     String currentdate = df.format(cal.getTime());
//         Date cur = df.parse(currentdate);
//         
//             Date Ddate= df.parse(txtdate.getText());
//
//         
//          if(Ddate.getTime() >= cur.getTime())
//                    {
       if(Integer.parseInt(duration) > 0){
//         
      
           try {
               
               String q="INSERT INTO emp_leave(EmpID,Leave_type,Date,Leave_Begin,Leave_End,Purpose,Status,Comment,Duration) values('"+id+"','"+type+"','"+date+"','"+begin+"','"+end+"','"+pur+"','"+pen+"','"+com+"','"+duration+"')";
              // String q="INSERT INTO emp_leave values("+id+"','"+type+"','"+date+"','"+begin+"','"+end+"','"+pur+"','"+pen+"','"+com+"')";
               
           pst=c.prepareStatement(q);
           pst.execute();
        //    jLabel10.setText("");
        cbtype.setSelectedIndex(0);
     //   txtdate.setText("");
        txtbegin.setText("");
        txtend.setText("");
        txtpurpose.setText("");
               
           } catch (Exception e) {
               
               JOptionPane.showMessageDialog(rootPane, e);
           }
               
  
           
         }
       else{
       
           JOptionPane.showMessageDialog(null, "Date is not valid,Please enter the correct date","", JOptionPane.ERROR_MESSAGE);
       }
       
       
            
       }           
//      }
//        
//          else
//                   {
//                        JOptionPane.showMessageDialog(null, "Date is not valid,Please enter the correct date","", JOptionPane.ERROR_MESSAGE);
//                    }
       
        } 
        
        
        
        
       
       catch (Exception e) {
                       e.printStackTrace();
           }  
     
        
       
       
       
       
          
          
          
           
       
        
      
       
     
                                
    
                                        
                               
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
         DatePicker Dp = new DatePicker(this);
        txtbegin.setText(Dp.setPickedDate());
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DatePicker Dp = new DatePicker(this);
        txtend.setText(Dp.setPickedDate());
        
        
          SimpleDateFormat myformat = new  SimpleDateFormat("yyyy-MM-dd");
        String inputString1 = txtbegin.getText();
        String inputString2 = txtend.getText();
        
        try {
            Date date1 = myformat.parse(inputString1);
            Date date2 = myformat.parse(inputString2);
            long diff = date2.getTime() - date1.getTime();
            String d = String.valueOf(diff / (24 * 60 * 60 * 1000));
            txtduration.setText(d);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                      new addLeave().setVisible(true);
                } catch (Exception e) {
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtbegin;
    private javax.swing.JLabel txtdate;
    private javax.swing.JLabel txtduration;
    private javax.swing.JLabel txtend;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtpurpose;
    // End of variables declaration//GEN-END:variables
}
