/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package staff;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Deerasinghe
 */
public final class addMembers extends javax.swing.JFrame {
    
     Connection con = null;
    PreparedStatement std = null;
    ResultSet rs = null;
    String ppid;

    /**
     * Creates new form addMembers
     */
    public addMembers() throws ClassNotFoundException, SQLException {
        
        initComponents();
         con = DB.mycon();
         table();
            // String ppid;
             table2();
       phoneformat.setVisible(false);
       emailformat.setVisible(false);
       nicformat.setVisible(false);
    
    }

    int addMembers(String x) {
        initComponents();
      //  jTabbedPane1.setSelectedIndex(1).setVisible(true);
        return -1;
    }
    
    
      addMembers(String ppid)
    {
             initComponents();
       // ppid=id;
        id.setText(ppid);
        
        getid();
    
    }
      
     
    
       public void getid(){
      
          try {
              
              Connection con =DB.mycon();
              Statement s=con.createStatement();
                   rs = s.executeQuery("SELECT * FROM add_staff where id='"+id+"' ");
                   while(rs.next()){
                       name.setText("name");
                   
                   
                   } 
                   
          } catch (Exception e) {
          }
      
      
      }
   
    
    
    
    public void table() throws SQLException{
        String sql = "Select Employee_Id,Employee_Name,Designation,Gender,Phone,Current_Address,E_Mail,NIC from add_staff";
        std = con.prepareStatement(sql);
        rs = std.executeQuery();
       
          jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }
    public void table2() throws SQLException{
         
        String p = "Pending";
        String sql = "select EmpID,Leave_type,Date,Leave_Begin,Leave_End,Purpose,Status,Duration from emp_leave where Status='"+p+"'";
        std = con.prepareStatement(sql);
        rs = std.executeQuery();
       
          jTable3.setModel(DbUtils.resultSetToTableModel(rs));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        nicformat = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox();
        department = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        qualifications = new javax.swing.JTextArea();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        name = new javax.swing.JTextField();
        designation = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        currentaddress = new javax.swing.JTextArea();
        phone = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        permenentaddress = new javax.swing.JTextArea();
        phoneformat = new javax.swing.JLabel();
        emailformat = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField12 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        leavetype = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 51, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/add.png"))); // NOI18N
        jButton7.setText("ADD");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 130, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/cancel.png"))); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 130, 35));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Details"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Department");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 90, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("NIC");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 50, 20));

        nic.setBackground(new java.awt.Color(204, 204, 255));
        nic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nicMouseClicked(evt);
            }
        });
        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        jPanel6.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 140, 30));

        jDateChooser2.setBackground(new java.awt.Color(204, 204, 255));
        jDateChooser2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser2MouseClicked(evt);
            }
        });
        jPanel6.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 140, 30));

        nicformat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nicformat.setForeground(new java.awt.Color(255, 0, 0));
        nicformat.setText("Format:123456789V");
        jPanel6.add(nicformat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, 20));

        gender.setBackground(new java.awt.Color(204, 204, 255));
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Gender", "Male", "Female" }));
        gender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genderMouseClicked(evt);
            }
        });
        jPanel6.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 140, 30));

        department.setBackground(new java.awt.Color(204, 204, 255));
        department.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departmentMouseClicked(evt);
            }
        });
        jPanel6.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 140, 30));

        qualifications.setBackground(new java.awt.Color(204, 204, 255));
        qualifications.setColumns(10);
        qualifications.setRows(3);
        jScrollPane1.setViewportView(qualifications);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 140, 90));

        jDateChooser1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 140, 30));

        name.setBackground(new java.awt.Color(204, 204, 255));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel6.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 140, 30));

        designation.setBackground(new java.awt.Color(204, 204, 255));
        designation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select one", "Sergent", "Senior Head Officer(SHO)", "Medical Officer(MO)", "Doctor", "Matorent", "Sister", "Nurse", "Attendant", "Labours", "Clarical Staff" }));
        designation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                designationItemStateChanged(evt);
            }
        });
        designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationActionPerformed(evt);
            }
        });
        jPanel6.add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee Name");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 19));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Designation");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 76, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Join Date");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 76, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Qualifications");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date of Birth");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 20));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover4.jpg"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, 430));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, 450));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Details"));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 34, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Current Address");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 70, -1, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Permenant Address");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 156, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("E-Mail");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 238, -1, -1));

        email.setBackground(new java.awt.Color(204, 204, 255));
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });
        jPanel7.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 140, -1));

        currentaddress.setBackground(new java.awt.Color(204, 204, 255));
        currentaddress.setColumns(10);
        currentaddress.setRows(3);
        currentaddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                currentaddressMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(currentaddress);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 140, 70));

        phone.setBackground(new java.awt.Color(204, 204, 255));
        phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneMouseClicked(evt);
            }
        });
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel7.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 140, 30));

        permenentaddress.setBackground(new java.awt.Color(204, 204, 255));
        permenentaddress.setColumns(10);
        permenentaddress.setRows(3);
        permenentaddress.setTabSize(3);
        permenentaddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                permenentaddressMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(permenentaddress);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 140, -1));

        phoneformat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        phoneformat.setForeground(new java.awt.Color(255, 0, 0));
        phoneformat.setText("Format:0112 602 100 ");
        phoneformat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneformatMouseClicked(evt);
            }
        });
        jPanel7.add(phoneformat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 149, -1));

        emailformat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailformat.setForeground(new java.awt.Color(255, 0, 0));
        emailformat.setText("Format:xxx@gmail.com");
        jPanel7.add(emailformat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover4.jpg"))); // NOI18N
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 440, 270));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 400, 290));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Deatils"));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setBackground(new java.awt.Color(204, 204, 255));
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        jPanel8.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 140, -1));

        username.setBackground(new java.awt.Color(204, 204, 255));
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        jPanel8.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 140, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Password");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" Username");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover3.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, 100));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 400, 120));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 70, 10));

        jLabel1.setText("Employee ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        jTabbedPane1.addTab("Add Members", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 102));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/Search.png"))); // NOI18N
        jButton6.setText("search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 120, 40));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable1);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 860, 380));
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Designation", "Employee_Id", "Employee_Name" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, 40));

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 51, 102));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/Delete.png"))); // NOI18N
        jButton13.setText("delete");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 130, -1));

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 51, 102));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/update.png"))); // NOI18N
        jButton14.setText("Edit Profile");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 140, -1));

        jButton1.setText("Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 80, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/back (2).jpg"))); // NOI18N
        jLabel23.setText("jLabel23");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 490));

        jTabbedPane1.addTab("View Member List", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setBackground(new java.awt.Color(204, 204, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable3);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 470, 190));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Employee ID");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Status");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        id1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id1.setText("id");
        jPanel3.add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 130, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Leave Type");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select one", "Pending", "Approve", "Disapprove", "Send to Manager" }));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Comment");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jTextField2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 130, 60));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/apply.png"))); // NOI18N
        jButton2.setText("Approve");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 140, 40));

        leavetype.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        leavetype.setText("leave type");
        jPanel3.add(leavetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 130, 20));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover4.jpg"))); // NOI18N
        jLabel27.setText("jLabel27");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 370, 420));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 360, 420));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 930, -1));

        jTabbedPane1.addTab("Leave Managment", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 116, 910, 510));

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/15106-illustration-of-a-red-close-button-pv.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 30, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/logo2.jpg"))); // NOI18N
        jLabel25.setText("jLabel5");
        jLabel25.setPreferredSize(new java.awt.Dimension(940, 110));
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String ID = id1.getText().toString();
        String LeaveType =leavetype.getText().toString();
        String Status = jComboBox2.getSelectedItem().toString();
        String Comment =jTextField2.getText().toString();

        int a= JOptionPane.showConfirmDialog(null,"Do you want to apply this leave ?");
        if(a==0)
        {
            try
            {
                con=DB.mycon();
                Statement s=con.createStatement();

                s.executeUpdate( "UPDATE emp_leave SET Status = '"+Status+"',Comment = '"+Comment+"' where EmpID='"+ID+"'");
                // std = con.prepareStatement(sq);
                // std.executeUpdate();

         id1.setText("");
         leavetype.setText("");      
         jComboBox2.setSelectedIndex(0);
         jTextField2.setText("");
         
         
         table2();
        // table3();
                
            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:

        int r=jTable3.getSelectedRow();
        try{
            String ID =jTable3.getValueAt(r, 0).toString();
            String LeaveType= jTable3.getValueAt(r, 1).toString();

            id1.setText(ID);
            leavetype.setText(LeaveType);

        }catch(NullPointerException n){
            JOptionPane.showMessageDialog(null, " Fiedld cannot be null","",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

        // TODO add your handling code here:
        new members(ppid).setVisible(true);
        //this.dispose();
        //this.dispose();
        //jPanel1.setVisible(true);

        // jTabbedPane1.setSelectedIndex(1);

        // members m1=new  members();

        // m1.setVisible(true);
        // this.dispose();

        /*
        try {

            String idd= id.getText();
            String Name=name.getText();
            String desig=designation.getSelectedItem().toString();
            String Date= date.getText();
            String quli=qualifications.getText();
            String dep=department.getText();
            String Birth=birth.getText();
            String Gender= gender.getSelectedItem().toString();
            String Phone= phone.getText();
            String Caddress= currentaddress.getText();
            String Paddress=permenentaddress.getText();
            String Email= email.getText();
            String Uname=username.getText();
            String Pword=  password.getText();

            Connection c=DB.mycon();
            Statement s=c.createStatement();

            s.executeUpdate(" UPDATE add_staff SET Employee_Name='"+Name+"',Designation='"+desig+"',Join_Date='"+Date+"' ,Qulifications='"+quli+"' ,Department='"+dep+"',Date_of_Birth='"+Birth+"',Gender='"+Gender+"',Phone='"+Phone+"',Current_Address='"+Caddress+"' ,Permenent_Address='"+Paddress+"',E_Mail='"+Email+"',User_Name='"+Uname+"',Password='"+Pword+"'  where Employee_Id='"+idd+"' ");
            // s.executeUpdate(" UPDATE add_staff SET Employee_Name='"+Name+"' where Employee_Id='"+idd+"' ");
            JOptionPane.showMessageDialog(null, " Staff Member Updating Successfull","",JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "sdfsdf");
        }

        */

    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:

        int x=JOptionPane.showConfirmDialog(null,"Do you want to delete this record??" );
        String NIC = nic.getText();
        try {
            con =DB.mycon();
            Statement s=con.createStatement();
            s.executeUpdate("delete  from add_staff where NIC = '"+ NIC +"'");
            table() ;
        } catch (Exception e) {
        }

        if(x==0)
        {

        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        int r=jTable1.getSelectedRow();
        try{
            ppid=jTable1.getValueAt(r, 0).toString();
            String Name= jTable1.getValueAt(r, 1).toString();
            String Designation=jTable1.getValueAt(r, 2).toString();
           // String Date = jTable1.getValueAt(r, 3).toString();
           // String Qualifications =jTable1.getValueAt(r, 4).toString();
           // String Department = jTable1.getValueAt(r, 5).toString();
           // String DateOfBirth =jTable1.getValueAt(r, 6).toString();
            String Gender = jTable1.getValueAt(r, 3).toString();
            String Phone = jTable1.getValueAt(r, 4).toString();
            String CurrentAddress = jTable1.getValueAt(r, 5).toString();
           // String PermenentAddress = jTable1.getValueAt(r, 10).toString();
            String Email = jTable1.getValueAt(r, 6).toString();
           // String Username = jTable1.getValueAt(r, 12).toString();
           // String Password =  jTable1.getValueAt(r, 13).toString();
            String NIC=  jTable1.getValueAt(r, 7).toString();

            id.setText(ppid);
            name.setText(Name);
            designation.setSelectedItem(Designation);

          //  qualifications.setText(Qualifications);
            nic.setText(NIC);
            //department.setText(Department);
           // birth.setText(DateOfBirth);
            gender.setSelectedItem(Gender);
            phone.setText(Phone);
            currentaddress.setText(CurrentAddress);
           // permenentaddress.setText(PermenentAddress);
            email.setText(Email);
           // username.setText(Username);
            //password.setText(Password);

        }catch(NullPointerException n){
            JOptionPane.showMessageDialog(null, " Fiedld cannot be null","",JOptionPane.INFORMATION_MESSAGE);
            
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        String result =jTextField12.getText();
        String type = jComboBox1.getSelectedItem().toString();

        try {
            String sql = "Select * from add_staff where "+type+" LIKE '%"+ result +"%'";

            std = con.prepareStatement(sql);
            rs = std.executeQuery();

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        id.setText("");
        name.setText("");
        designation.setSelectedIndex(0);
        ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText("");
        qualifications.setText("");
        department.setText("");
        ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).setText("");
        gender.setSelectedIndex(0);
        phone.setText("");
        currentaddress.setText("");
        permenentaddress.setText("");
        email.setText("");
        username.setText("");
        password.setText("");

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        // if(!name.getText().equals(""))
        if(!name.getText().equals("") && designation.getSelectedIndex()!=0 &&  !qualifications.getText().equals("") && !department.getText().equals("") && gender.getSelectedIndex()!=0 && !phone.getText().equals("") && !currentaddress.getText().equals("") && !permenentaddress.getText().equals("") && !email.getText().equals("") && !username.getText().equals("") && !password.getText().equals(""))
        // if(!name.getText().equals("") && designation.getSelectedIndex()!=0 )
        {
            String pattern="[0-9]+";
            String pattern1="[a-zA-Z ]+";
            
             
            String Nic=nic.getText();
            if(Nic.length()==10 &&Nic.charAt(9)=='V')
            {

            //  String Name = name.getText();
            // if(!name.getText().equals("") && Name.matches(pattern1))

            String Phone = phone.getText();
            if(Phone.length()==10 && Phone.matches(pattern) )
            {

                String EMAIL_REGEX = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
                String Email = email.getText();
                if(Email.matches(EMAIL_REGEX))
                {
                    // {
                       // String Id = id.getText();
                        String Name = name.getText();
                        String Designation = designation.getSelectedItem().toString();
                        String date=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
                        //  String date=date.getText();
                        String Qualifications = qualifications.getText();
                        String Department = department.getText().toString();
                         String Birth=((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
                        String Gender = gender.getSelectedItem().toString();
                        String NIC=nic.getText();

                        String CurrentAddress = currentaddress.getText();
                        String PermenentAddress = permenentaddress.getText();
                        // String Email = email.getText();
                        String Username = username.getText();
                        String Password = password.getText();
                        //String Password2 = password2.getText();
                        //if(!name.getText().equals("") && designation.getSelectedIndex()!=0 &&  !qualifications.getText().equals("") && !department.getText().equals("") && !birth.getText().equals("") && gender.getSelectedIndex()!=0.equals("") && !phone.getText().equals("") && !currentaddress.getText().equals("") && !permenentaddress.getText().equals("") && !email.getText().equals("") && !username.getText().equals("") )

                        // String Name = name.getText();

                        int a= JOptionPane.showConfirmDialog(null,"Do you want to add this employee?");
                        if(a==0)
                        {
                            try
                            {

                                String sql="INSERT INTO add_staff (Employee_Name,Designation,Join_Date,Qulifications,Department,Date_of_Birth,Gender,Phone,Current_Address,Permenent_Address,E_Mail,User_Name,Password,NIC) values ('"+ Name+"','"+Designation+"','"+date+"','"+Qualifications+"','"+Department+"','"+Birth+"','"+Gender+"','"+Phone+"','"+CurrentAddress+"','"+PermenentAddress+"','"+Email+"','"+Username +"','"+Password+"','"+NIC+"')";
                                std = con.prepareStatement(sql);
                                std.executeUpdate();
                                table();
                                
                                id.setText("");
                                name.setText("");
                                designation.setSelectedIndex(0);
                                ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText("");
                                qualifications.setText("");
                                department.setText("");
                                 ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).setText("");
                                gender.setSelectedIndex(0);
                                phone.setText("");
                                currentaddress.setText("");
                                permenentaddress.setText("");
                                email.setText("");
                                username.setText("");
                                password.setText("");


                            } catch (Exception e)
                            {
                                JOptionPane.showMessageDialog(null, "Record is already exits","",JOptionPane.ERROR_MESSAGE);
                            }
                              
            
                        }

                    }

                    else
                    {
                        JOptionPane.showMessageDialog(null, "Invalid Email Details","",JOptionPane.ERROR_MESSAGE);
                    }

                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Invalid contact number Details","",JOptionPane.ERROR_MESSAGE);
                }

                // else
                // {
                    //JOptionPane.showMessageDialog(null, "Invalid Name Details","",JOptionPane.ERROR_MESSAGE);
                    // }
            
            }
            else
            {
            JOptionPane.showMessageDialog(null, "Invalid NIC Details","",JOptionPane.ERROR_MESSAGE);
            }

            
            
            }

            else
            {
                JOptionPane.showMessageDialog(null, "Enter Essential Details","",JOptionPane.ERROR_MESSAGE);
            }

          
    }//GEN-LAST:event_jButton7ActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void designationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designationActionPerformed

    private void designationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_designationItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_designationItemStateChanged

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void phoneformatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneformatMouseClicked
        // TODO add your handling code here:
   
    }//GEN-LAST:event_phoneformatMouseClicked

    private void phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseClicked
        // TODO add your handling code here:
             phoneformat.setVisible(true);
              nicformat.setVisible(false);
    }//GEN-LAST:event_phoneMouseClicked

    private void currentaddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentaddressMouseClicked
        // TODO add your handling code here:
        phoneformat.setVisible(false);
         nicformat.setVisible(false);
    }//GEN-LAST:event_currentaddressMouseClicked

    private void permenentaddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_permenentaddressMouseClicked
        // TODO add your handling code here:
        
        phoneformat.setVisible(false);
         nicformat.setVisible(false);
    }//GEN-LAST:event_permenentaddressMouseClicked

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
        emailformat.setVisible(true);
        phoneformat.setVisible(false);
         nicformat.setVisible(false);
    }//GEN-LAST:event_emailMouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        // TODO add your handling code here:
        phoneformat.setVisible(false);
         emailformat.setVisible(false);
          nicformat.setVisible(false);
    }//GEN-LAST:event_usernameMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        // TODO add your handling code here:
        phoneformat.setVisible(false);
         emailformat.setVisible(false);
          nicformat.setVisible(false);
    }//GEN-LAST:event_passwordMouseClicked

    private void nicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nicMouseClicked
        // TODO add your handling code here:
        nicformat.setVisible(true);
    }//GEN-LAST:event_nicMouseClicked

    private void departmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departmentMouseClicked
        // TODO add your handling code here:
        nicformat.setVisible(false);
    }//GEN-LAST:event_departmentMouseClicked

    private void jDateChooser2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser2MouseClicked
        // TODO add your handling code here:
        nicformat.setVisible(false);
    }//GEN-LAST:event_jDateChooser2MouseClicked

    private void genderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genderMouseClicked
        // TODO add your handling code here:
        nicformat.setVisible(false);
    }//GEN-LAST:event_genderMouseClicked

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
            HashMap param=new HashMap();
//param.put("reportParameterName",valueForTheParameter);
MyiReportViewer viewer=new MyiReportViewer("C:\\Users\\X55OL\\Desktop\\reports\\staff.jasper",param);
viewer.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new addMembers().setVisible(true);
                    
                } catch (Exception e) {
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea currentaddress;
    private javax.swing.JTextField department;
    private javax.swing.JComboBox designation;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailformat;
    private javax.swing.JComboBox gender;
    private javax.swing.JTextField id;
    private javax.swing.JLabel id1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel leavetype;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nic;
    private javax.swing.JLabel nicformat;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextArea permenentaddress;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phoneformat;
    private javax.swing.JTextArea qualifications;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
