/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package staff;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Deerasinghe
 */
public final class members extends javax.swing.JFrame {

   Connection con = null;
    PreparedStatement std = null;
    ResultSet rs = null;
    String Ppid;
    /**
     * Creates new form members
     */
    public members() throws ClassNotFoundException, SQLException {
      
           initComponents();
           con=DB.mycon();
         //  String ppid;
      
    }
    
    
     
     members(String ppid)
    {
             initComponents();
             
       // ppid=id;
        id.setText(ppid);
        
        Ppid = ppid ;
        getid(Ppid);
    
    }
    
      public void getid(String Ppid){
      
          try {
              
              Connection c=DB.mycon();
              Statement s=c.createStatement();
              
                   rs = s.executeQuery("SELECT * FROM add_staff where Employee_Id='"+Ppid+"' ");
                   while(rs.next()){
                       name.setText(rs.getString("Employee_Name"));
                       designation.setSelectedItem(rs.getString("Designation"));
                       date.setText(rs.getString("Join_Date"));
                       qualifications.setText(rs.getString("Qulifications"));
                       department.setText(rs.getString("Department"));
                       birth.setText(rs.getString("Date_of_Birth"));
                       gender.setSelectedItem(rs.getString("Gender"));
                       phone.setText(rs.getString("Phone"));
                        currentaddress.setText(rs.getString("Current_Address"));
                       permenentaddress.setText(rs.getString("Permenent_Address"));
                       email.setText(rs.getString("E_Mail"));
                       username.setText(rs.getString("User_Name"));
                       password.setText(rs.getString("Password"));
                       nic.setText(rs.getString("NIC"));
                       
                       
                           
        
                   } 
                   
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, e);
          }
      
      
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        qualifications = new javax.swing.JTextArea();
        designation = new javax.swing.JComboBox();
        name = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        date = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        department = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        birth = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        email = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        permenentaddress = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        currentaddress = new javax.swing.JTextArea();
        phone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Employee Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 19));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Designation");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 76, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Join Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 76, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Qualifications");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        qualifications.setColumns(20);
        qualifications.setRows(5);
        jScrollPane1.setViewportView(qualifications);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 140, 70));

        designation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select a Designation", "Sergent/VOG", "Senior Head Officer(SHO)", "Medical Officer(MO)", "Matorent", "Sister", "Nurse", "Attendant", "Labours", "Clarical Staff" }));
        designation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                designationItemStateChanged(evt);
            }
        });
        designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationActionPerformed(evt);
            }
        });
        getContentPane().add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 140, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 140, -1));

        jButton8.setBackground(new java.awt.Color(0, 102, 204));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("X");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 40, 20));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/update.png"))); // NOI18N
        jButton7.setText("UPDATE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 150, 40));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 140, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Details"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Department");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 70, -1));
        jPanel1.add(birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Date of Birth");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Gender", "Male", "Female" }));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 140, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("NIC");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        jPanel1.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 140, -1));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 24, 60, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Employee ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 460));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Details"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 130, -1));

        permenentaddress.setColumns(20);
        permenentaddress.setRows(5);
        jScrollPane3.setViewportView(permenentaddress);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 130, 60));

        currentaddress.setColumns(20);
        currentaddress.setRows(5);
        jScrollPane2.setViewportView(currentaddress);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, 60));
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 130, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Phone");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Current Address");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Permenant Address");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("E-Mail");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 280, 290));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Details"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Employee Usename");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Employee Password");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 280, 110));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/back (2).jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 630, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void designationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_designationItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_designationItemStateChanged

    private void designationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designationActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
          if(!name.getText().equals("") && designation.getSelectedIndex()!=0 &&  !qualifications.getText().equals("") && !department.getText().equals("") && gender.getSelectedIndex()!=0 && !phone.getText().equals("") && !currentaddress.getText().equals("") && !permenentaddress.getText().equals("") && !email.getText().equals("") && !username.getText().equals("") && !password.getText().equals(""))
        // if(!name.getText().equals("") && designation.getSelectedIndex()!=0 )
        {
              
              
               String pattern="[0-9]+";
            String pattern1="[a-zA-Z ]+";
            
             
            String Nic=nic.getText();
            if(Nic.length()==10 &&Nic.charAt(9)=='V')
            {
                
                
                 String Phone = phone.getText();
            if(Phone.length()==10 && Phone.matches(pattern) )
            {
                
                
                String EMAIL_REGEX = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
                String Email = email.getText();
                if(Email.matches(EMAIL_REGEX))
                {
        
        int x=JOptionPane.showConfirmDialog(null,"Do you want to update this record??" );

        try{
        String Id = id.getText();
        String Name = name.getText();
        String Designation = designation.getSelectedItem().toString();
        String Date = date.getText().toString();
        String Qualifications = qualifications.getText();
        String Department = department.getText().toString();
        String DateOfBirth =birth.getText().toString();
        String Gender = gender.getSelectedItem().toString();
        String Phhone =phone.getText().toString();
        String CurrentAddress = currentaddress.getText();
        String PermenentAddress = permenentaddress.getText();
        String Emmail = email.getText();
        String Username = username.getText();
        String Password = password.getText();
        String NIC = nic.getText();

        
            Connection con =DB.mycon();
            Statement s=con.createStatement();
           // s.executeUpdate( "UPDATE add_staff SET Employee_Name='"+Name+"',Designation='"+Designation+"', ");
        //  String sql = "UPDATE add_staff SET Employee_Name='"+Name+"' ";
           s.executeUpdate("UPDATE add_staff SET Employee_Name ='"+Name+"',Designation='"+Designation+"',Qulifications='"+Qualifications+"',Department='"+Department+"',Date_of_Birth='"+DateOfBirth+"',Gender='"+Gender+"',Phone='"+Phhone+"',Current_Address='"+CurrentAddress+"',Permenent_Address='"+PermenentAddress+"',E_Mail='"+Emmail+"',User_Name='"+Username+"',Password='"+Password+"',NIC='"+NIC+"' where Employee_Id='"+Id+"' ");
           
          
          // jTabbedPane1.setSelectedIndex(1).setVisible(true);
           addMembers ad = new addMembers();
          
         //  ad.panel();
            ad.setVisible(true);
           this.dispose();
           
           
           
          //  std = con.prepareStatement(sql);
        //    std.executeUpdate();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
          //  System.out.println(e);
        }

        
        
        
                    }

                    else
                    {
                        JOptionPane.showMessageDialog(null, "Invalid Email Details","",JOptionPane.ERROR_MESSAGE);
                    }
        
        
          }
                else
                {
                    JOptionPane.showMessageDialog(null, "Invalid contact number Details","",JOptionPane.ERROR_MESSAGE);
                }
        
          
            }
            else
            {
            JOptionPane.showMessageDialog(null, "Invalid NIC Details","",JOptionPane.ERROR_MESSAGE);
            }
        
       
            }

            else
            {
                JOptionPane.showMessageDialog(null, "Enter Essential Details","",JOptionPane.ERROR_MESSAGE);
            }  
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
        //new addMembers().setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new members().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birth;
    private javax.swing.JTextArea currentaddress;
    private javax.swing.JTextField date;
    private javax.swing.JTextField department;
    private javax.swing.JComboBox designation;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox gender;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nic;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextArea permenentaddress;
    private javax.swing.JTextField phone;
    private javax.swing.JTextArea qualifications;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
