/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patient;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Isurunath
 */
public final class IPDRegister1 extends javax.swing.JFrame {
 Connection c=null;
    PreparedStatement pst =null;
    ResultSet rs=null;
        String x;
        String pid;
    
    /**
     * Creates new form NewJFrame2
     */
    public IPDRegister1() {
        initComponents();
        tableload2();
         getid();
         
         
         Calendar javaCalendar = null;
        String currentDate = " ";

        javaCalendar = Calendar.getInstance();

      
       // currentDate = javaCalendar.get(Calendar.DATE) + "-" + (javaCalendar.get(Calendar.MONTH) + 1) + "-" + javaCalendar.get(Calendar.YEAR);
        currentDate =  javaCalendar.get(Calendar.YEAR) + "-" + (javaCalendar.get(Calendar.MONTH) )+ "-" + javaCalendar.get(Calendar.DATE); ;
        
        txtrdate2.setText(currentDate);
         
    }
    
    
    public  void tableload2(){

        try {
            
            String sql="SELECT  pid,rdate,name,dob,age,gender,blood,nic,address,contact,guard,email,dept,wardno,wardname,cons     from p2";
            c=DB.mycon();
            pst=c.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable7.setModel(DbUtils.resultSetToTableModel(rs));
               
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    }
    
    public void getid(){
        
        try {
            
            
             Connection c = DB.mycon();
             java.sql.Statement s=c.createStatement();
             ResultSet rs = s.executeQuery("SELECT * FROM p2 where pid='"+x+"'");
             
             while(rs.next()){
                txtpid2.setText(rs.getString("pid"));
                
                
                
                txtrdate2.setText(rs.getString("rdate"));
                txtname2.setText(rs.getString("name"));
                  txtdob2.setText(rs.getString("dob"));
                    txtage2.setText(rs.getString("age"));
                    cgen2.setSelectedItem(rs.getString("gender"));
                    cblood2.setSelectedItem(rs.getString("blood"));
                    txtnic2.setText(rs.getString("nic"));
                    txtadd2.setText(rs.getString("address"));

                    txtcno2.setText(rs.getString("contact"));
                    txtgurad2.setText(rs.getString("guard"));
                    txtemail2.setText(rs.getString("email"));
                    txtdept2.setText(rs.getString("dept"));
                    txtcons2.setText(rs.getString("cons"));
                    txtwardno.setText(rs.getString("wardno"));
                    txtwardname.setText(rs.getString("wardname"));
                    //txtpres.getText();
               // namelabel.setText(rs.getString("name"));
             }
                
         
            
        } catch (Exception e) {
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel69 = new javax.swing.JLabel();
        txtpid2 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        txtname2 = new javax.swing.JTextField();
        txtage2 = new javax.swing.JTextField();
        cgen2 = new javax.swing.JComboBox();
        cblood2 = new javax.swing.JComboBox();
        jLabel58 = new javax.swing.JLabel();
        txtnic2 = new javax.swing.JTextField();
        txtrdate2 = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        txtdob2 = new javax.swing.JTextField();
        jButton23 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        txtgurad2 = new javax.swing.JTextField();
        txtadd2 = new javax.swing.JTextField();
        txtcno2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtemail2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        txtdept2 = new javax.swing.JTextField();
        txtwardno = new javax.swing.JTextField();
        txtwardname = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        txtcons2 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(940, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel69.setText("Patients ID");
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        txtpid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpid2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtpid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 90, -1));

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Details"));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Registerd Date");
        jPanel13.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Name");
        jPanel13.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Date Of Birth");
        jPanel13.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Age");
        jPanel13.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Blood Group");
        jPanel13.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Gender");
        jPanel13.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtname2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel13.add(txtname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 120, -1));

        txtage2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel13.add(txtage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, -1));

        cgen2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel13.add(cgen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 120, -1));

        cblood2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B +", "B-", "AB+", "AB-", "O" }));
        jPanel13.add(cblood2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 120, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("NIC");
        jPanel13.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txtnic2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel13.add(txtnic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 120, -1));

        txtrdate2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel13.add(txtrdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 120, -1));

        jButton22.setText("D");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 40, -1));

        txtdob2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel13.add(txtdob2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, -1));

        jButton23.setText("D");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 40, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel13.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 320, -1));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 310, 290));

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Detatils"));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Address");
        jPanel14.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Contact No");
        jPanel14.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Guardian");
        jPanel14.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtgurad2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel14.add(txtgurad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 130, -1));

        txtadd2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel14.add(txtadd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, -1));

        txtcno2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel14.add(txtcno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 130, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Email");
        jPanel14.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtemail2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel14.add(txtemail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 130, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover2.jpg"))); // NOI18N
        jLabel4.setText("jLabel2");
        jPanel14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -10, 510, -1));

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 290, 290));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Hospital Details"));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Department");
        jPanel15.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Cosultant");
        jPanel15.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtdept2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel15.add(txtdept2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 130, -1));

        txtwardno.setBackground(new java.awt.Color(204, 204, 255));
        txtwardno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwardnoActionPerformed(evt);
            }
        });
        jPanel15.add(txtwardno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 130, -1));

        txtwardname.setBackground(new java.awt.Color(204, 204, 255));
        txtwardname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwardnameActionPerformed(evt);
            }
        });
        jPanel15.add(txtwardname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, -1));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Ward No");
        jPanel15.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Ward Name");
        jPanel15.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtcons2.setBackground(new java.awt.Color(204, 204, 255));
        txtcons2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcons2ActionPerformed(evt);
            }
        });
        jPanel15.add(txtcons2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 130, -1));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/update.png"))); // NOI18N
        jButton13.setText("Register");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 150, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover2.jpg"))); // NOI18N
        jLabel6.setText("jLabel2");
        jPanel15.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -10, 600, -1));

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 280, 290));

        jTable7.setBackground(new java.awt.Color(204, 204, 255));
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable7MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable7);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 900, 180));

        jButton1.setText("View Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 120, -1));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 70, -1));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 70, -1));

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 70, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/out.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 30, 30));

        jButton7.setText("Report");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 433, 120, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/logo2.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setPreferredSize(new java.awt.Dimension(940, 110));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 950, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtpid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpid2ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        DatePicker Dp=new DatePicker(this);
        txtrdate2.setText(Dp.setPickedDate());
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        DatePicker Dp=new DatePicker(this);
        txtdob2.setText(Dp.setPickedDate());
    }//GEN-LAST:event_jButton23ActionPerformed

    private void txtwardnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwardnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwardnoActionPerformed

    private void txtwardnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwardnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwardnameActionPerformed

    private void txtcons2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcons2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcons2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:

        if(!txtrdate2.getText().toString().equals("")&&!txtname2.getText().toString().equals("")&&!txtdob2.getText().toString().equals("")&&!txtage2.getText().toString().equals("")&&!cgen2.getSelectedItem().toString().equals("")&&!cblood2.getSelectedItem().toString().equals("")&&!txtnic2.getText().toString().equals("")&&!txtadd2.getText().toString().equals("")&&!txtcno2.getText().toString().equals("")&&!txtgurad2.getText().toString().equals("")&&!txtemail2.getText().toString().equals("")&&!txtdept2.getText().toString().equals("")&&!txtwardno.getText().toString().equals("")&&!txtwardname.getText().toString().equals("")&&!txtcons2.getText().toString().equals(""))
        {
            
             String pattern="[0-9]+";
     String pattern1="[a-zA-Z ]+";
    
            
            String nic=txtnic2.getText();
            if(nic.length()==10 &&nic.charAt(9)=='V')
            {

                String EMAIL_REGEX = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
                String email = txtemail2.getText();
                if(email.matches(EMAIL_REGEX))
                {
                    String contact = txtcno2.getText();
                    if(contact.length()==10 && contact.matches(pattern) )
            
                        {
                
                // String name = txtname2.getText();
                           // if(!txtname2.getText().equals("") && name.matches(pattern))
              //   if(!txtname2.getText().equals("") )
                             //  {
                
                    
//                    File f=jFileChooser1.getSelectedFile();
//                                String path=f.getAbsolutePath();
//                                path=path.replace("\\", "/");

                    String rdate=txtrdate2.getText();
                    String name=txtname2.getText();
                    String dob=txtdob2.getText();
                    String age=txtage2.getText();
                    String gender=cgen2.getSelectedItem().toString();
                    String blood=cblood2.getSelectedItem().toString();
                    //String nic=txtnic2.getText();
                    String address=txtadd2.getText();

                   // String contact=txtcno2.getText();
                    String guard=txtgurad2.getText();
                    // String email=txtemail2.getText();

                    String dept=txtdept2.getText();
                    String cons=txtcons2.getText();
                    String wardno=txtwardno.getText();
                    String wardname=txtwardname.getText();
                    //  String pres=txtpres.getText();

                    try {

                        Connection c=DB.mycon();
                        Statement s=c.createStatement();
                        s.executeUpdate("INSERT INTO p2 (rdate,name,dob,age,gender,blood,nic,address,contact,guard,email,dept,wardno,wardname,cons) values ('"+rdate+"','"+name+"','"+dob+"','"+age+"','"+gender+"','"+blood+"','"+nic+"','"+address+"','"+contact+"','"+guard+"','"+email+"','"+dept+"','"+wardno+"','"+wardname+"','"+cons+"' )");
                        tableload2();
                        JOptionPane.showMessageDialog(null, " Patient Registration Successfull","",JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        //  JOptionPane.showMessageDialog(null, e);
                             JOptionPane.showMessageDialog(null, "Duplicate NIC Details","",JOptionPane.ERROR_MESSAGE);
                    }
                    // JOptionPane.showMessageDialog(null, "Successfully Registered","",JOptionPane.OK_CANCEL_OPTION);

                    //JOptionPane.showMessageDialog(null, "Successfully Registered","",JOptionPane.INFORMATION_MESSAGE);
                   // JOptionPane.showMessageDialog(null, " Patient Registration Successfull","",JOptionPane.INFORMATION_MESSAGE);
                     
                    txtpid2.setText("");
                    txtrdate2.setText("");
                    txtname2.setText("");
                    txtdob2.setText("");
                    txtage2.setText("");
                     
                    txtnic2.setText("");
                    txtadd2.setText("");

                    txtcno2.setText("");
                    txtgurad2.setText("");
                    txtemail2.setText("");
                    txtdept2.setText("");
                    txtwardno.setText("");
                    txtwardname.setText("");
                    txtcons2.setText("");
                    //txtpres.setText("");
                   // lblimg.setIcon(null);
//                      lblimg.setIcon(null);
//                     lblpath.setText("");
                    
               // }
                 
                //  else
               // {
               //   JOptionPane.showMessageDialog(null, "Invalid Name Details","",JOptionPane.ERROR_MESSAGE);
              // }
                 
                 
                    }
                     else
                        {
                    JOptionPane.showMessageDialog(null, "Invalid contact number Details","",JOptionPane.ERROR_MESSAGE);
                         }

            
                    }

                         else
                         {
                            JOptionPane.showMessageDialog(null, "Invalid Email Details","",JOptionPane.ERROR_MESSAGE);
                          }

            }

            else
            {
                JOptionPane.showMessageDialog(null, "Invalid NIC Details","",JOptionPane.ERROR_MESSAGE);
            }
            
                               
            
        }

        else
        {
            JOptionPane.showMessageDialog(null, "Enter Essential Details","",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTable7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable7MouseClicked
        // TODO add your handling code here:

        int r=jTable7.getSelectedRow();

        pid=jTable7.getValueAt(r,0).toString();
        String rdate=jTable7.getValueAt(r,1).toString();
        String name=jTable7.getValueAt(r,2).toString();
        String dob=jTable7.getValueAt(r,3).toString();
        String age=jTable7.getValueAt(r,4).toString();
        String gender=jTable7.getValueAt(r,5).toString();
        String blood=jTable7.getValueAt(r,6).toString();
        String nic=jTable7.getValueAt(r,7).toString();
        String address=jTable7.getValueAt(r,8).toString();
        String contact=jTable7.getValueAt(r,9).toString();
        String guard=jTable7.getValueAt(r,10).toString();

        String email=jTable7.getValueAt(r,11).toString();

        String dept=jTable7.getValueAt(r,12).toString();
        String wardno=jTable7.getValueAt(r,13).toString();
        String wardname=jTable7.getValueAt(r,14).toString();
        String cons=jTable7.getValueAt(r,15).toString();
       // String path=jTable7.getValueAt(r, 16).toString();
        
        txtpid2.setText(pid);
        txtrdate2.setText(rdate);
        txtname2.setText(name);
        txtdob2.setText(dob);
        txtage2.setText(age);
        cgen2.setSelectedItem(gender);
        cblood2.setSelectedItem(blood);
        txtnic2.setText(nic);
        txtadd2.setText(address);

        txtcno2.setText(contact);
        txtgurad2.setText(guard);

        txtemail2.setText(email);

        txtdept2.setText(dept);
        txtwardno.setText(wardno);
        txtwardname.setText(wardname);
        txtcons2.setText(cons);
        // txtpres.setText(pres);
//         lblpath.setText(path);

    }//GEN-LAST:event_jTable7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        new patientprofile1(pid).setVisible(true);
       // opdpatientprofile2(pid).setvVisible(true);
        this.dispose(); 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
           try {
            Connection c=DB.mycon();
            Statement s=c.createStatement();
            ResultSet rs=s.executeQuery("SELECT * FROM p2 WHERE pid='"+txtpid2.getText()+"'");

            while(rs.next()){

                txtrdate2.setText(rs.getString("rdate"));
                txtname2.setText(rs.getString("name"));
                txtdob2.setText(rs.getString("dob"));
                txtage2.setText(rs.getString("age"));
                cgen2.setSelectedItem(rs.getString("gender"));
                cblood2.setSelectedItem(rs.getString("blood"));
                txtnic2.setText(rs.getString("nic"));
                txtadd2.setText(rs.getString("address"));

                txtcno2.setText(rs.getString("contact"));
                txtgurad2.setText(rs.getString("guard"));
                txtemail2.setText(rs.getString("email"));
                txtdept2.setText(rs.getString("dept"));
                txtwardno.setText(rs.getString("wardno"));
                txtwardname.setText(rs.getString("wardname"));
                txtcons2.setText(rs.getString("cons"));
                //lblpath.setText(rs.getString("image")); 

            }
            
//            File f1=new File(lblpath.getText().toString());
//        
//        Image im=ImageIO.read(f1);
//        im=im.getScaledInstance(lblimg.getWidth(),lblimg.getHeight(),Image.SCALE_SMOOTH);
//        lblimg.setIcon(new ImageIcon(im));
    

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
             int x=JOptionPane.showConfirmDialog(rootPane,"DO YOU WANT TO DELETE?????");
                 if( x==0){  
            Connection c=DB.mycon();
            Statement s= c.createStatement();
              s.executeUpdate("DELETE FROM p2 WHERE pid='"+txtpid2.getText()+"'");
             // int x=JOptionPane.showConfirmDialog(rootPane,"DO YOU WANT TO DELETE?????");
              JOptionPane.showMessageDialog(null, " Patient Deletion Successfull","",JOptionPane.INFORMATION_MESSAGE);
               
                    txtpid2.setText("");
                    txtrdate2.setText("");
                    txtname2.setText("");
                    txtdob2.setText("");
                    txtage2.setText("");
                     
                    txtnic2.setText("");
                    txtadd2.setText("");

                    txtcno2.setText("");
                    txtgurad2.setText("");
                    txtemail2.setText("");
                    txtdept2.setText("");
                    txtwardno.setText("");
                    txtwardname.setText("");
                    txtcons2.setText("");
//                      lblimg.setIcon(null);
//                     lblpath.setText("");
                    tableload2();
                 }
                 
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                    String pid=txtpid2.getText();
                  String rdate=txtrdate2.getText();
                    String name=txtname2.getText();
                    String dob=txtdob2.getText();
                    String age=txtage2.getText();
                    String gender=cgen2.getSelectedItem().toString();
                    String blood=cblood2.getSelectedItem().toString();
                    String nic=txtnic2.getText();
                    String address=txtadd2.getText();

                    String contact=txtcno2.getText();
                    String guard=txtgurad2.getText();
                     String email=txtemail2.getText();

                    String dept=txtdept2.getText();
                    String cons=txtcons2.getText();
                    String wardno=txtwardno.getText();
                    String wardname=txtwardname.getText();
                    
                    
//                     File f=jFileChooser1.getSelectedFile();
//        String path=f.getAbsolutePath();
//        path=path.replace("\\", "/");
//                    
        try {
            
            int x =JOptionPane.showConfirmDialog(null,"Do you want to update?");
        if(x==0)
        {
             Connection c=DB.mycon();
        Statement s=c.createStatement();
       // s.executeUpdate(" UPDATE p2 SET rdate='"+rdate+"',name='"+name+"',dob='"+dob+"' ,age='"+age+"', gender='"+gender+"',blood='"+blood+"',nic='"+nic+"',address='"+address+"',conatct='"+contact+"',guard='"+guard+"',email='"+email+"',dept='"+dept+"',wardno='"+wardno+"',wardname='"+wardname+"',cons='"+cons+"' where pid='"+pid+"'");
        s.executeUpdate(" UPDATE p2 SET rdate='"+rdate+"',name='"+name+"',dob='"+dob+"',age='"+age+"' ,gender='"+gender+"' ,blood='"+blood+"',nic='"+nic+"',address='"+address+"',contact='"+contact+"',guard='"+guard+"' ,email='"+email+"',dept='"+dept+"',wardno='"+wardno+"',wardname='"+wardname+"',cons='"+cons+"' where pid='"+pid+"' ");
         JOptionPane.showMessageDialog(null, " Patient Updating Successfull","",JOptionPane.INFORMATION_MESSAGE);
        tableload2();
        }
        
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
                    txtpid2.setText("");
                    txtrdate2.setText("");
                    txtname2.setText("");
                    txtdob2.setText("");
                    txtage2.setText("");
                     
                    txtnic2.setText("");
                    txtadd2.setText("");

                    txtcno2.setText("");
                    txtgurad2.setText("");
                    txtemail2.setText("");
                    txtdept2.setText("");
                    txtwardno.setText("");
                    txtwardname.setText("");
                    txtcons2.setText("");
//                      lblimg.setIcon(null);
//                     lblpath.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new PatientHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     try {
            HashMap param=new HashMap();
//param.put("reportParameterName",valueForTheParameter);
staff.MyiReportViewer viewer=new staff.MyiReportViewer("C:\\Users\\X55OL\\Desktop\\reports\\patient.jasper",param);
viewer.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IPDRegister1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IPDRegister1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IPDRegister1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IPDRegister1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IPDRegister1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cblood2;
    private javax.swing.JComboBox cgen2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextField txtadd2;
    private javax.swing.JTextField txtage2;
    private javax.swing.JTextField txtcno2;
    private javax.swing.JTextField txtcons2;
    private javax.swing.JTextField txtdept2;
    private javax.swing.JTextField txtdob2;
    private javax.swing.JTextField txtemail2;
    private javax.swing.JTextField txtgurad2;
    private javax.swing.JTextField txtname2;
    private javax.swing.JTextField txtnic2;
    private javax.swing.JTextField txtpid2;
    private javax.swing.JTextField txtrdate2;
    private javax.swing.JTextField txtwardname;
    private javax.swing.JTextField txtwardno;
    // End of variables declaration//GEN-END:variables
}
