/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patient;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SAM
 */
public final class number extends javax.swing.JFrame {

    
    Connection c=null;
    PreparedStatement pst =null;
    ResultSet rs=null;
     String x;
        String ppid;
        String pid;
    /**
     * Creates new form OPDRegister2
     */
    public number() {
        initComponents();
        tableload2();
        getid();
         Calendar javaCalendar = null;
        String currentDate = " ";

        javaCalendar = Calendar.getInstance();

      
       // currentDate = javaCalendar.get(Calendar.DATE) + "-" + (javaCalendar.get(Calendar.MONTH) + 1) + "-" + javaCalendar.get(Calendar.YEAR);
        currentDate =  javaCalendar.get(Calendar.YEAR) + "-" + (javaCalendar.get(Calendar.MONTH) )+ "-" + javaCalendar.get(Calendar.DATE); ;
        
        txtrdate.setText(currentDate);
    }

      public  void tableload2(){

        try {
            String sql="SELECT * from p1";
            c=DB.mycon();
            pst=c.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            
                    
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    }
      
      
       public void getid(){
        
        try {
            
            
             Connection c = DB.mycon();
             java.sql.Statement s=c.createStatement();
             ResultSet rs = s.executeQuery("SELECT * FROM p2 where pid='"+x+"'");
             
             while(rs.next()){
                txtpid.setText(rs.getString("pid"));
                
                
                
                txtrdate.setText(rs.getString("rdate"));
                txtname.setText(rs.getString("name"));
                  txtdob.setText(rs.getString("dob"));
                    txtage.setText(rs.getString("age"));
                    cgen.setSelectedItem(rs.getString("gender"));
                    cblood.setSelectedItem(rs.getString("blood"));
                    txtnic.setText(rs.getString("nic"));
                    txtadd.setText(rs.getString("address"));

                    txtcno.setText(rs.getString("contact"));
                    txtgurad.setText(rs.getString("guard"));
                    //txtemail.setText(rs.getString("email"));
                    txtdept.setText(rs.getString("dept"));
                    txtcons.setText(rs.getString("cons"));
                    //txtwardno.setText(rs.getString("wardno"));
                    //txtwardname.setText(rs.getString("wardname"));
                    txtpres.getText();
               // namelabel.setText(rs.getString("name"));
             }
                
         
            
        } catch (Exception e) {
        }
        
    }
       
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser2 = new javax.swing.JFileChooser();
        jTextField1 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        cgen = new javax.swing.JComboBox();
        cblood = new javax.swing.JComboBox();
        jLabel79 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        txtrdate = new javax.swing.JTextField();
        jButton24 = new javax.swing.JButton();
        txtdob = new javax.swing.JTextField();
        jButton25 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        txtgurad = new javax.swing.JTextField();
        txtadd = new javax.swing.JTextField();
        txtcno = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        txtdept = new javax.swing.JTextField();
        txtcons = new javax.swing.JTextField();
        txtpres = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        lblpath = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblimg = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(940, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel70.setText("Patients ID");
        getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));
        getContentPane().add(txtpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 90, 30));

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Details"));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel72.setText("Registerd Date");
        jPanel17.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel73.setText("Name");
        jPanel17.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel74.setText("DOB");
        jPanel17.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel75.setText("Age");
        jPanel17.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel76.setText("Blood Group");
        jPanel17.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel77.setText("Gender");
        jPanel17.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        jPanel17.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 110, -1));
        jPanel17.add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 110, -1));

        cgen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        cgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgenActionPerformed(evt);
            }
        });
        jPanel17.add(cgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 110, -1));

        cblood.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O" }));
        jPanel17.add(cblood, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 110, -1));

        jLabel79.setText("NIC");
        jPanel17.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        jPanel17.add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 110, -1));
        jPanel17.add(txtrdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 110, -1));

        jButton24.setText("D");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 50, -1));
        jPanel17.add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 110, -1));

        jButton25.setText("D");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 50, -1));

        getContentPane().add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 340, 300));

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Details"));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel81.setText("Address");
        jPanel18.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel82.setText("Contact No");
        jPanel18.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel83.setText("Guardian");
        jPanel18.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel18.add(txtgurad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 120, -1));
        jPanel18.add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 120, -1));
        jPanel18.add(txtcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, -1));

        getContentPane().add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 360, 130));

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel86.setText("Department");
        jPanel19.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel87.setText("Cosultant");
        jPanel19.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel88.setText("Prescriptions");
        jPanel19.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        jPanel19.add(txtdept, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 120, -1));

        txtcons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconsActionPerformed(evt);
            }
        });
        jPanel19.add(txtcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 120, -1));

        txtpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpresActionPerformed(evt);
            }
        });
        jPanel19.add(txtpres, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 120, -1));

        jButton7.setText("Browse");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 120, 20));

        lblpath.setText("Path");
        jPanel19.add(lblpath, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 50, -1));

        jLabel1.setText("Upload Image");
        jPanel19.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        getContentPane().add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 360, 160));

        jButton26.setText("Register");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, 140, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PatientsID", "Reg Date", "Name", "DOB", "Age", "Gender", "Blood", "NIC", "Address", "Contact No", "Guardian", "Department", "Consultant", "Prescriptions"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 890, 150));

        jButton1.setText("View Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 110, 30));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 70, 30));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, 30));

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 80, 30));

        jButton5.setText("update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 80, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/out.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/logo2.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");
        jLabel6.setPreferredSize(new java.awt.Dimension(940, 110));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        lblimg.setBackground(new java.awt.Color(153, 153, 255));
        lblimg.setText("Image");
        getContentPane().add(lblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 150, 200));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel7.setText("jLabel1");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 950, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        DatePicker Dp=new DatePicker(this);
        txtrdate.setText(Dp.setPickedDate());
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        DatePicker Dp=new DatePicker(this);
        txtdob.setText(Dp.setPickedDate());
    }//GEN-LAST:event_jButton25ActionPerformed

    private void txtconsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconsActionPerformed

    private void txtpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpresActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        // if(!txtrdate.getText().toString().equals("")&&!txtname.getText().toString().equals("")&&!txtdob.getText().toString().equals("")&&!txtage.getText().toString().equals("")&&!cgen.getSelectedItem().toString().equals("")&&!cblood.getSelectedItem().toString()&&!txtnic.getText().toString().equals("")&&!txtadd.getText().toString().equals("")&&!txtcno.getText().toString().equals(""))
        if(!txtrdate.getText().toString().equals("")&&!txtname.getText().toString().equals("")&&!txtdob.getText().toString().equals("")&&!txtage.getText().toString().equals("")&&!cgen.getSelectedItem().toString().equals("")&&!cblood.getSelectedItem().toString().equals("")&&!txtnic.getText().toString().equals("")&&!txtadd.getText().toString().equals("")&&!txtcno.getText().toString().equals("")&&!txtgurad.getText().toString().equals("")&&!txtdept.getText().toString().equals("")&&!txtcons.getText().toString().equals("")&&!txtpres.getText().toString().equals(""))
        {
            String pattern="[0-9]+";
            
            String nic=txtnic.getText();
            if(nic.length()==10 &&nic.charAt(9)=='V')
            {
                String contact=txtcno.getText();    
                    
                         if(contact.length()==10 && contact.matches(pattern) ){
                            
                             File f=jFileChooser2.getSelectedFile();
                                String path=f.getAbsolutePath();
                                path=path.replace("\\", "/");
                
                String rdate=txtrdate.getText();
                String name=txtname.getText();
                String dob=txtdob.getText();
                String age=txtage.getText();
                String gender=cgen.getSelectedItem().toString();
                String blood=cblood.getSelectedItem().toString();
                //  String nic=txtnic.getText();
                String address=txtadd.getText();

              //  String contact=txtcno.getText();
                String guard=txtgurad.getText();
                String dept=txtdept.getText();
                String cons=txtcons.getText();
                String pres=txtpres.getText();

                try {
                    Connection c=DB.mycon();
                    Statement s=c.createStatement();
                    String q;
                    //s.executeUpdate("INSERT INTO p1 (rdate,name,dob) values ('"+rdate+"','"+name+"','"+dob+"')");

                    q=("INSERT INTO p1 (rdate,name,dob,age,gender,blood,nic,address,contact,guard,dept,consult,pres,image) values ('"+rdate+"','"+name+"','"+dob+"','"+age+"','"+gender+"','"+blood+"','"+nic+"','"+address+"','"+contact+"','"+guard+"','"+dept+"','"+cons+"','"+pres+"' ,'"+path+"')");

                    pst=c.prepareStatement(q);
                    pst.execute();
                    
                       JOptionPane.showMessageDialog(null, " Patient Registration Successfull","",JOptionPane.INFORMATION_MESSAGE);
                     tableload2();
                } catch (Exception e) {
                   // e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Duplicate NIC Details","",JOptionPane.ERROR_MESSAGE);
                }
              
                // JOptionPane.showMessageDialog(null, "Successfully Registered","",JOptionPane.OK_CANCEL_OPTION);
               // JOptionPane.showMessageDialog(null, " Patient Registration Successfull","",JOptionPane.INFORMATION_MESSAGE);

                txtrdate.setText("");
                txtname.setText("");
                txtdob.setText("");
                txtage.setText("");
                cgen.setSelectedIndex(0);
                cblood.setSelectedIndex(0);
                txtnic.setText("");
                txtadd.setText("");

                txtcno.setText("");
                txtgurad.setText("");
                txtdept.setText("");
                txtcons.setText("");
                txtpres.setText("");
                 lblimg.setIcon(null);
                        
                        }
                         else
            {
                JOptionPane.showMessageDialog(null, "Invalid Contact Details","",JOptionPane.ERROR_MESSAGE);
            }
                        
                        
                        }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid NIC Details","",JOptionPane.ERROR_MESSAGE);
            }
        }

        else
        {
            JOptionPane.showMessageDialog(null, "Enter Essential Details","",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton26ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        int r=jTable1.getSelectedRow();

         pid=jTable1.getValueAt(r,0).toString();
        String rdate=jTable1.getValueAt(r,1).toString();
        String name=jTable1.getValueAt(r,2).toString();
        String dob=jTable1.getValueAt(r,3).toString();
        String age=jTable1.getValueAt(r,4).toString();
        String gender=jTable1.getValueAt(r,5).toString();
        String blood=jTable1.getValueAt(r,6).toString();
        String nic=jTable1.getValueAt(r,7).toString();
        String address=jTable1.getValueAt(r,8).toString();
        String contact=jTable1.getValueAt(r,9).toString();
        String guard=jTable1.getValueAt(r,10).toString();
        String dept=jTable1.getValueAt(r,11).toString();
        String cons=jTable1.getValueAt(r,12).toString();
        String pres=jTable1.getValueAt(r,13).toString();
        String path=jTable1.getValueAt(r, 14).toString();
        
        
        txtpid.setText(pid);
        txtrdate.setText(rdate);
        txtname.setText(name);
        txtdob.setText(dob);
        txtage.setText(age);
        cgen.setSelectedItem(gender);
        cblood.setSelectedItem(blood);
        txtnic.setText(nic);
        txtadd.setText(address);

        txtcno.setText(contact);
        txtgurad.setText(guard);
        txtdept.setText(dept);
        txtcons.setText(cons);
        txtpres.setText(pres);
           lblpath.setText(path);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new opdpatientprofile33(pid).setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            int x=JOptionPane.showConfirmDialog(rootPane,"DO YOU WANT TO DELETE?????");
                 if( x==0){ 
            
            Connection c=DB.mycon();
            Statement s= c.createStatement();
              s.executeUpdate("DELETE FROM p1 WHERE pid='"+txtpid.getText()+"'");
              JOptionPane.showMessageDialog(null, " Patient Deletion Successfull","",JOptionPane.INFORMATION_MESSAGE);
              
              txtpid.setText("");
              txtrdate.setText("");
                txtname.setText("");
                txtdob.setText("");
                txtage.setText("");
                cgen.setSelectedIndex(0);
                cblood.setSelectedIndex(0);
                txtnic.setText("");
                txtadd.setText("");

                txtcno.setText("");
                txtgurad.setText("");
                txtdept.setText("");
                txtcons.setText("");
                txtpres.setText("");
                   lblimg.setIcon(null);
                   lblpath.setText("");
                tableload2();
                 }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try {
            Connection c=DB.mycon();
            Statement s=c.createStatement();
            ResultSet rs=s.executeQuery("SELECT * FROM p1 WHERE pid='"+txtpid.getText()+"'");

            while(rs.next()){

              txtrdate.setText(rs.getString("rdate"));
                txtname.setText(rs.getString("name"));
               txtdob.setText(rs.getString("dob"));
                txtage.setText(rs.getString("age"));
                cgen.setSelectedItem(rs.getString("gender"));
                cblood.setSelectedItem(rs.getString("blood"));
                txtnic.setText(rs.getString("nic"));
                txtadd.setText(rs.getString("address"));

                txtcno.setText(rs.getString("contact"));
                txtgurad.setText(rs.getString("guard"));
               // txtemail3.setText(rs.getString("email"));
                txtdept.setText(rs.getString("dept"));
               // txtwardno3.setText(rs.getString("wardno"));
               // txtwardname3.setText(rs.getString("wardname"));
                txtcons.setText(rs.getString("consult"));
                   txtpres.setText(rs.getString("pres"));
                   lblpath.setText(rs.getString("image")); 
            }
            
            File f1=new File(lblpath.getText().toString());
        
        Image im=ImageIO.read(f1);
        im=im.getScaledInstance(lblimg.getWidth(),lblimg.getHeight(),Image.SCALE_SMOOTH);
        lblimg.setIcon(new ImageIcon(im));
            

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        txtpid.setText("");
              txtrdate.setText("");
                txtname.setText("");
                txtdob.setText("");
                txtage.setText("");
                cgen.setSelectedIndex(0);
                cblood.setSelectedIndex(0);
                txtnic.setText("");
                txtadd.setText("");

                txtcno.setText("");
                txtgurad.setText("");
                txtdept.setText("");
                txtcons.setText("");
                txtpres.setText("");
                   lblimg.setIcon(null);
                     lblpath.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String rdate=txtrdate.getText();
                String name=txtname.getText();
                String dob=txtdob.getText();
                String age=txtage.getText();
                String gender=cgen.getSelectedItem().toString();
                String blood=cblood.getSelectedItem().toString();
                  String nic=txtnic.getText();
                String address=txtadd.getText();

                String contact=txtcno.getText();
                String guard=txtgurad.getText();
                String dept=txtdept.getText();
                String cons=txtcons.getText();
                String pres=txtpres.getText();
                    
                
                 File f=jFileChooser2.getSelectedFile();
        String path=f.getAbsolutePath();
        path=path.replace("\\", "/");
                
                try {
                     int x =JOptionPane.showConfirmDialog(null,"Do you want to update?");
        if(x==0)
        {
            Connection c=DB.mycon();
            Statement s=c.createStatement();
            s.executeUpdate("UPDATE p1 SET rdate ='"+rdate+"',name='"+name+"',dob='"+dob+"',age='"+age+"',gender='"+gender+"',blood='"+blood+"',nic='"+nic+"',address='"+address+"',contact='"+contact+"',guard='"+guard+"',dept='"+dept+"',consult='"+cons+"',pres='"+pres+"',image='"+path+"' WHERE pid='"+pid+"' ");
               JOptionPane.showMessageDialog(null, " Patient Updating Successfull","",JOptionPane.INFORMATION_MESSAGE);
               tableload2();
               }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         try {
            jFileChooser2.showOpenDialog(this);
            File f=jFileChooser2.getSelectedFile();
            String path=f.getAbsolutePath();
            path=path.replace("\\", "/");
                File f1=new File(path);
        
        Image im=ImageIO.read(f1);
        im=im.getScaledInstance(lblimg.getWidth(),lblimg.getHeight(),Image.SCALE_SMOOTH);
        lblimg.setIcon(new ImageIcon(im));
        
        
    } catch (Exception e) {
         JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cgenActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new PatientHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(number.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(number.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(number.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(number.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new number().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cblood;
    private javax.swing.JComboBox cgen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblimg;
    private javax.swing.JLabel lblpath;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcno;
    private javax.swing.JTextField txtcons;
    private javax.swing.JTextField txtdept;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtgurad;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtpres;
    private javax.swing.JTextField txtrdate;
    // End of variables declaration//GEN-END:variables
}
