/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patient;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Isurunath
 */
public final class patientprofile1 extends javax.swing.JFrame {
     Connection c=null;
    PreparedStatement pst =null;
    ResultSet rs=null;
        String x;
        String ppid;
        
    
    /**
     * Creates new form patientprofile
     */
    public patientprofile1() {
        initComponents();
        getid();
        tableload2();
    }
    
    public patientprofile1( String pid) {
        initComponents();
        ppid =pid;
        jLabel5.setText(ppid);
        getid();
        tableload2();
        
    }
     public void getid(){
        
        try {
            
            
             c = DB.mycon();
             Statement s=c.createStatement();
             rs = s.executeQuery("SELECT * FROM p2 where pid= '"+ppid+"'");
             
             while(rs.next()){
               // txtpid3.setText(rs.getString("pid"));
                txtrdate3.setText(rs.getString("rdate"));
                txtname3.setText(rs.getString("name"));
                txtdob3.setText(rs.getString("dob"));
                txtage3.setText(rs.getString("age"));
                cgen33.setText(rs.getString("gender"));
                cblood33.setText(rs.getString("blood"));
                txtnic3.setText(rs.getString("nic"));
                txtadd3.setText(rs.getString("address"));

                txtcno3.setText(rs.getString("contact"));
                txtgurad3.setText(rs.getString("guard"));
                txtemail3.setText(rs.getString("email"));
                txtdept3.setText(rs.getString("dept"));
                txtwardno3.setText(rs.getString("wardno"));
                txtwardname3.setText(rs.getString("wardname"));
                txtcons3.setText(rs.getString("cons"));
//                lblpath.setText(rs.getString("image")); 
                    //txtpres.getText();
               // namelabel.setText(rs.getString("name"));
             }
                
//         File f1=new File(lblpath.getText().toString());
//        
//        Image im=ImageIO.read(f1);
//        im=im.getScaledInstance(lblimg.getWidth(),lblimg.getHeight(),Image.SCALE_SMOOTH);
//        lblimg.setIcon(new ImageIcon(im));
//    
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(rootPane, "Select User");
        }
     }
     
     public  void tableload2(){

        try {
            
            String sql="SELECT * from paclinic3 where id='"+ppid+"'";
            c=DB.mycon();
            pst=c.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            
                    
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtrdate3 = new javax.swing.JLabel();
        txtname3 = new javax.swing.JLabel();
        txtdob3 = new javax.swing.JLabel();
        txtage3 = new javax.swing.JLabel();
        txtnic3 = new javax.swing.JLabel();
        cgen33 = new javax.swing.JLabel();
        cblood33 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        txtadd3 = new javax.swing.JLabel();
        txtcno3 = new javax.swing.JLabel();
        txtgurad3 = new javax.swing.JLabel();
        txtemail3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtdept3 = new javax.swing.JLabel();
        txtwardno3 = new javax.swing.JLabel();
        txtwardname3 = new javax.swing.JLabel();
        txtcons3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblpath = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(940, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(0, 102, 204));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Details"));
        jPanel4.setPreferredSize(new java.awt.Dimension(870, 570));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registerd Date");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date Of Birth");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Age");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Blood Group");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gender");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NIC");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        txtrdate3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtrdate3.setForeground(new java.awt.Color(0, 0, 102));
        txtrdate3.setText("Date");
        jPanel4.add(txtrdate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 80, -1));

        txtname3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtname3.setForeground(new java.awt.Color(0, 0, 102));
        txtname3.setText("name");
        jPanel4.add(txtname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 80, -1));

        txtdob3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdob3.setForeground(new java.awt.Color(0, 0, 102));
        txtdob3.setText("dob");
        jPanel4.add(txtdob3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 80, 20));

        txtage3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtage3.setForeground(new java.awt.Color(0, 0, 102));
        txtage3.setText("age");
        jPanel4.add(txtage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 80, -1));

        txtnic3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnic3.setForeground(new java.awt.Color(0, 0, 102));
        txtnic3.setText("nic");
        jPanel4.add(txtnic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 80, -1));

        cgen33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cgen33.setForeground(new java.awt.Color(0, 0, 102));
        cgen33.setText("gender");
        jPanel4.add(cgen33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 70, -1));

        cblood33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cblood33.setForeground(new java.awt.Color(0, 0, 102));
        cblood33.setText("blood");
        jPanel4.add(cblood33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 80, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patients ID");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("id");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 30, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover4.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 260));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 290, 280));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Details"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Address");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contact No");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Guardian");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Email");
        jPanel5.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtadd3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtadd3.setForeground(new java.awt.Color(0, 0, 102));
        txtadd3.setText("address");
        jPanel5.add(txtadd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 80, -1));

        txtcno3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcno3.setForeground(new java.awt.Color(0, 0, 102));
        txtcno3.setText("contact");
        jPanel5.add(txtcno3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 80, -1));

        txtgurad3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtgurad3.setForeground(new java.awt.Color(0, 0, 102));
        txtgurad3.setText("guardian");
        jPanel5.add(txtgurad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 80, -1));

        txtemail3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtemail3.setForeground(new java.awt.Color(0, 0, 102));
        txtemail3.setText("email");
        jPanel5.add(txtemail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 80, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover4.jpg"))); // NOI18N
        jLabel8.setText("jLabel7");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 260));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 270, 280));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Hospital Details"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Department");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Cosultant");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Ward No");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Ward Name");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtdept3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdept3.setForeground(new java.awt.Color(0, 0, 102));
        txtdept3.setText("department");
        jPanel6.add(txtdept3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 80, -1));

        txtwardno3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtwardno3.setForeground(new java.awt.Color(0, 0, 102));
        txtwardno3.setText("wardno");
        jPanel6.add(txtwardno3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 80, -1));

        txtwardname3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtwardname3.setForeground(new java.awt.Color(0, 0, 102));
        txtwardname3.setText("wardname");
        jPanel6.add(txtwardname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 80, -1));

        txtcons3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcons3.setForeground(new java.awt.Color(0, 0, 102));
        txtcons3.setText("consultant");
        jPanel6.add(txtcons3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 80, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/cover4.jpg"))); // NOI18N
        jLabel17.setText("jLabel7");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 260));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 290, 280));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/update.png"))); // NOI18N
        jButton2.setText("Prescriptions");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        jTable2.setBackground(new java.awt.Color(204, 204, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 900, 120));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff/image/out.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 30, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/logo2.jpg"))); // NOI18N
        jLabel13.setText("jLabel5");
        jLabel13.setPreferredSize(new java.awt.Dimension(940, 110));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        lblpath.setText("Path");
        getContentPane().add(lblpath, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test2/images/blue.jpg"))); // NOI18N
        jLabel6.setText("jLabel1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 950, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         new prescriptions(ppid).setVisible(true);
        this.dispose(); 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new PatientHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientprofile1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientprofile1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientprofile1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientprofile1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientprofile1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cblood33;
    private javax.swing.JLabel cgen33;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblpath;
    private javax.swing.JLabel txtadd3;
    private javax.swing.JLabel txtage3;
    private javax.swing.JLabel txtcno3;
    private javax.swing.JLabel txtcons3;
    private javax.swing.JLabel txtdept3;
    private javax.swing.JLabel txtdob3;
    private javax.swing.JLabel txtemail3;
    private javax.swing.JLabel txtgurad3;
    private javax.swing.JLabel txtname3;
    private javax.swing.JLabel txtnic3;
    private javax.swing.JLabel txtrdate3;
    private javax.swing.JLabel txtwardname3;
    private javax.swing.JLabel txtwardno3;
    // End of variables declaration//GEN-END:variables
}
